### ISSUE TITLE
Local vs. global search via the sitemap

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#12]
So...with the sitemap and search, do we need to provide the option to scope the search. eg. Search this site vs Search the university? 

Given we don't currently provide a search page template for a locally scoped search (do we need to do this as well?), and that I think it is potentially confusing for all searches to be uni-wide when you might be in the frame-of-mind of a local site another solution might be to simply do two searches at the same time and present the user with two panes of results? 

Ignoring the terrible colours I've used, this is what I was thinking. 

Step 1. 
![initial-display](https://f.cloud.github.com/assets/150315/2317331/375fd926-a34a-11e3-95e8-d91d160fb096.png)

Step 2
![on-keypress](https://f.cloud.github.com/assets/150315/2317334/3fc7948c-a34a-11e3-8577-fa275f420862.png)

Step 3
![search-state](https://f.cloud.github.com/assets/150315/2317335/4313b026-a34a-11e3-8412-17e882aa126d.png)

I also think we should make this sort of search available with a keypress from any page.

**Comment by waitingallday** [comment]
Is it time to start talking about this? Or post-v1.0

**Comment by herrweis** [comment]
This should come as soon as possible... We have to wait for the search to arrive though

**Comment by waitingallday** [comment]
Going to leave a milestone off for now, and re-label until we know more about search

**Comment by waitingallday** [comment]
There is a plan for search now, so I'm closing this issue.
