### ISSUE TITLE
Table headings don't match up for first entry on mobile

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#146]
![screen shot 2014-11-18 at 10 14 38 am](https://cloud.githubusercontent.com/assets/6847023/5079766/e86bba4a-6f0b-11e4-8f59-55abd7319465.png)

**Comment by waitingallday** [comment]
The mobile styles are limited to simple tables only, it can't deal with multi-column cells at the moment - this should be reflected in docs until we can figure out a solution.

**Comment by rothenburycam** [comment]
Hey @waitingallday, is there a workaround for this? What's the difference between 'complex' and 'simple' tables that you mentioned? 

Also, I still have the issue from #264 where one table has borders and the other doesn't. Can't figure out what's causing this...

**Comment by waitingallday** [comment]
By "complex", I mean tables with merged cells and/or multiple layers of headings. I've got a good fix for this that should be deployed this week, hopefully that will fix the border problem too. Will let you know as soon as it's ready!

**Comment by waitingallday** [comment]
There was a fix deployed for this back around v3.0 (sorry just catching up with issues), if you wrap the table with a `<div class="mobile-wrap">` it will pass the table directly through without applying the helper. This can be seen on the complex table examples 2 & 3 on http://web.unimelb.edu.au/components/tables/
