### ISSUE TITLE
Event listing looks a bit broken on IE10

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#153]
![screen shot 2014-11-18 at 4 39 38 pm](https://cloud.githubusercontent.com/assets/6847023/5083028/bcbd5120-6f41-11e4-96df-e7a27b4f0aa5.png)

**Comment by waitingallday** [comment]
Fixed in https://github.com/marcom-unimelb/unimelb-design-system/commit/d9817e6b48e9f9118133c628daccaec2bb3f93d3
