### ISSUE TITLE
Listings: text overflow and alignment issues on news and events 

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#155]
![screen shot 2014-11-18 at 4 51 20 pm](https://cloud.githubusercontent.com/assets/6847023/5083105/6f646f74-6f43-11e4-8e0b-d913cd3c3c1a.png)

**Comment by waitingallday** [comment]
This was fixed in https://github.com/marcom-unimelb/unimelb-design-system/commit/2fced19872df5433c935cd5cd51e4cbada1a3963 (items are now fixed height with gradient ellipsis)
