### ISSUE TITLE
desktop-nav active text display

### ISSUE THREAD

**Issue by rafaelgonzalez** [marcom-unimelb/unimelb-design-system#163]
When the string ends with one single character, it is sometimes displayed on a second line.

The behaviour seems random (depending on the last character)

![screen shot 2014-11-26 at 10 20 15 am](https://cloud.githubusercontent.com/assets/456921/5193502/dfe71f40-7555-11e4-9e52-d55455fb6558.png)
![screen shot 2014-11-26 at 10 20 32 am](https://cloud.githubusercontent.com/assets/456921/5193510/e7bd338a-7555-11e4-9bc1-bf1995e007ea.png)

**Comment by waitingallday** [comment]
I've just tried to recreate this problem with chrome and couldn't, so I wonder if it was a render bug that they've since fixed? Either way, I'll close this for now - reopen if you experience this again.

**Comment by rafaelgonzalez** [comment]
Yeah I can't reproduce it either.

The element's markup change a bit (compare screenshot below with the one in my previous comment), so maybe something about the way it was before triggered this behaviour.

![screen shot 2015-03-11 at 3 53 54 pm](https://cloud.githubusercontent.com/assets/456921/6590645/13ba9492-c807-11e4-98ec-d5349833d8b5.png)

Cheers :beers:
