### ISSUE TITLE
Use of non-recognised ARIA role 'tabs'

### ISSUE THREAD

**Issue by anormand** [marcom-unimelb/unimelb-design-system#174]
There is no recognised ARIA role of 'tabs'. However there is an ARIA role for 'tab', 'tablist' and 'tabpanel'.

tab:
A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user.

tablist:
A list of tab elements, which are references to tabpanel elements.

tabpanel:
A container for the resources associated with a tab, where each tab is contained in a tablist.

Files affected:
example_layouts/about.slim
example_layouts/course.slim
example_layouts/homepage.slim
example_layouts/mcm-lyrebird-start.slim
example_layouts/vca-course-overview.slim
example_layouts/vca-home.slim
tabs/01-full-width-navigation-tabs.slim
tabs/02-in-page-tabs.slim

**Comment by waitingallday** [comment]
Sounds good, the "tabs" went on a tab container, so "tabpanel" should do it. Thanks!
