### ISSUE TITLE
Use of non-recognised ARIA role 'sitemap'

### ISSUE THREAD

**Issue by anormand** [marcom-unimelb/unimelb-design-system#175]
There is no recognised ARIA role of 'sitemap'. the problem with using non-standard ARIA roles is that assistive technologies and browsers will not support them. 

Probably the most closely aligned role is 'navigation'. We could make a submission to the W3C arguing that 'sitemap' should be included in the role definitions as a sub-class of 'navigation'. But even if accepted it would be a while before it became supported. 

navigation:
A collection of navigational elements (usually links) for navigating the document or related documents.

Files affected:
injection/global-nav/_globalnav.scss
injection/global-nav/nav.coffee.erb
injection/header/header.coffee.erb

**Comment by waitingallday** [comment]
Unfortunately, we're already using role=navigation for the local nav - the role=sitemap is the global (static) one. This is completely my fault, and purely an implementation problem - I was happy with the consistency of using roles everywhere as selectors in the CSS and JS, but obviously that meant making one up when it doesn't exist. I'll need to re-architect some of this (carefully).

**Comment by anormand** [comment]
There is no reason that we can't use role=navigation for more than one landmark

**Comment by waitingallday** [comment]
There is, the way that I used it 😀 The JS is expecting a single object with role=navigation, I'll need to change to a different selector (aria roles were great for keeping the code concise, but it really should be on classes)
