### ISSUE TITLE
CMS content offset below header.

### ISSUE THREAD

**Issue by uomben** [marcom-unimelb/unimelb-design-system#178]
Matrix CMS places the WYSIWYG content within a DIV, which currently results in the content being shifted down by the height of the header.  Temporary fix was:

.uomcontent [role="main"] > *:first-child {
    padding-top: 0;
}

... better handled with a class name for the first div in the CMS(?)

**Comment by waitingallday** [comment]
There was absolutely a reason for doing this, but I can't exactly remember what that reason was :)

Rather than replacing the first-child selector, I'll add an additional class called

```css
.uomcontent [role="main"] .first-block
```

**Comment by waitingallday** [comment]
Looking over it again, I believe that was done to provide a clearance to the overhanging logo at desktop widths. Is there a reason for pushing the content hard up to the page header? In practise, we would always use a header element as the first child within .main ie.

```html
<div role="main">
  <header>
    <h1>Title of page</h1>
  </header>

  (actual page content starts here)
```

And this inherits that extra padding, while at the same time clearing the logo. It's still fine to go straight in without that header element, but that white space is needed:

![screen shot 2015-03-12 at 4 03 36 pm](https://cloud.githubusercontent.com/assets/863542/6612494/6a1d1808-c8d1-11e4-9123-912d90f97528.png)

(I'm going to drop this off the next milestone for now until we've properly discussed it)

**Comment by dkevey** [comment]
This is actually needed for the CMS to add some spacing to content. This would be applied to the first div  i.e.

.uomcontent [role="main"] .first-block {
    padding-top: 4.5rem;
}

![cms_first div](https://cloud.githubusercontent.com/assets/1305804/6914037/664f72b0-d7d2-11e4-84d1-6cfabd913be2.png)
![first-block](https://cloud.githubusercontent.com/assets/1305804/6914041/6b8ab492-d7d2-11e4-8234-4c9f26365365.png)

**Comment by herrweis** [comment]
Can you put it in a section?

**Comment by dkevey** [comment]
Hi Andi,

I have a couple of templates that use a section to wrap content, so those are fine, but I want to limit the number of templates I need to create and sometimes I need the flexibility.



Regards,


Donna Kevey


Web Manager

Marketing & Communications | Faculty of Business & Economics | The University of Melbourne

Level 12, 198 Berkeley Street Carlton, Victoria 3010 Australia

P: +61 3 8344 1693 | E: dkevey@unimelb.edu.au<mailto:dkevey@unimelb.edu.au> | W: www.fbe.unimelb.edu.au<http://www.fbe.unimelb.edu.au/>

**Comment by waitingallday** [comment]
I think this issue is probably out of date with how we're managing this at the moment - will close now. We are hoping to redo the spacing in a future update so that problems like this won't happen!
