### ISSUE TITLE
No clear directions on how to implement branding in mandated CMS

### ISSUE THREAD

**Issue by DanielTosello** [marcom-unimelb/unimelb-design-system#179]
In addition, some parts appear to be pretty much explicitly impossible...

Am I missing something?

Some directions would be great, thanks :)

**Comment by neilang** [comment]
Hi @DanielTosello there is a project underway to implement the design system in Matrix. However, was there something in particular you were having trouble with?

**Comment by DanielTosello** [comment]
I have deadlines to meet... when can i expect these templates? Should i just use the old one?

**Comment by neilang** [comment]
I can understand your frustration. Squiz are currently adapting the templates for general availability in the CMS but that project won't be completed for 2-3 months. However they are able to do ad-hoc build for a specific site if you need something sooner - you can contact @chazbatrouney (x40346) for the details.

**Comment by DanielTosello** [comment]
Thanks for the info Neil. If we could get enough info on how to include the
js and make it functional then that would be a start... That said we've
already started work with previous templates in the interim. We'll update
the page when the new templates are available. If it wasn't a new page for
a new platform it probably wouldn't be anywhere near as big an issue.

Can i suggest that you guys update web.unimelb.edu.au to actually display
the information that you've given me, and link to the old templates instead
of a 404? It will cause a lot less confusion for those who aren't aware of
the situation...

Thanks again for giving me a time and someone to contact... i do wish i had
a bit more time to help fix this.
--Daniel

**Comment by neilang** [comment]
No worries. Thanks for the feedback on web.unimelb, we'll add it to the list of things to do.
