### ISSUE TITLE
Staff listing Images off centre

### ISSUE THREAD

**Issue by tonyz** [marcom-unimelb/unimelb-design-system#184]
![screen shot 2015-02-02 at 4 56 04 pm](https://cloud.githubusercontent.com/assets/696178/5996375/83c1ecb8-aafc-11e4-9c1c-608e58e4345d.png)
Staff listing images are left aligned so we overcame this with inline styling.
Text was all centre aligned just the profile images were left aligned. System may need to be updated to rectify this problem

**Comment by herrweis** [comment]
Thanks Tony,

could you add a screenshot?

**Comment by tonyz** [comment]
screenshot added.

**Comment by waitingallday** [comment]
I believe this was resolved outside of a style fix in the system - please reopen if this is incorrect.

**Comment by tonyz** [comment]
Hi Jason,

At the time the page was built we used inline styles to get around the
problem. Haven't tested it since the fix in the system.


Tony Zara
0421279669
