### ISSUE TITLE
Portal Icon

### ISSUE THREAD

**Issue by anormand** [marcom-unimelb/unimelb-design-system#189]
During development of the new SSO page (https://my-prep.unimelb.edu.au), feedback was received by Liz Cashen that showing the “Portal” icon may be confusing. 

Her comments, outlined below, seem valid:

"Just wondering, where does the SSO take you…I.e. Does it take staff to staff hub and students to my.unimelb? If so, I’m wondering if we even need the “portals” tab?
 
But if we do, my suggestion would be:
-          “portal” changed to “portals” 
-          When you click on “portals”, change second screen to read:
o   CURRENT STUDENTS, ask.unimelb.edu.au (probably don’t need “click here”?)
o   STAFF MEMBER, staff hub (not staff portal, and probably don’t need “click here”?)
-   in any case, “staff portal” will definitely need to be changed to “staff hub” for accuracy."

**Comment by neilang** [comment]
I can confirm that after SSO it takes you to the right page. I agree with changing "staff portal" to "staff hub" and removing "click here".

**Comment by waitingallday** [comment]
No problem
