### ISSUE TITLE
Pathfinder blinking 

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#198]
Just noticed that on rollover (in Safari 8.0.3) the non-active pathfinder boxes blink in the same way as the active box. 

I guess that _could_ be intentional, but it feels weird...

See demo here: http://screencast.com/t/QynS1F8s

**Comment by waitingallday** [comment]
We looked into this, it appears to be a performance issue on CSS rendering: a combination of transforms and font rendering.

I don't think there is anything practical we can do at the moment, so I'll close this for now.
