### ISSUE TITLE
icons to be included

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#199]
Hi, are there plans to include icons to use please?
The last templates included document styles and we have found using icons is easier to scan pages for information rather than writing text all the time. 

Useful icons are; maps, email, phone, pdf (document), user (people), arrows for list styles. 

![icons](https://cloud.githubusercontent.com/assets/1305804/6434138/2cc87306-c0d6-11e4-8051-ef70b7410496.png)

**Comment by waitingallday** [comment]
Thanks Donna, I'll pass this along to @herrweis

**Comment by herrweis** [comment]
Hi Donna,

yes this is absolutely intended, but unfortunately at the moment we lack of time and people to do it. As soon as I get the chance to include them, I will!
