### ISSUE TITLE
Common imagery issues

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#2]
# Imagery

There are a variety of image related issues we run into

## Common issues with regards to imagery

* Images used that add no value to the message the page is trying to communicate
* Images added with text in them (which is not accessible or SEO friendly)
* Images added with text on top of them (and mobile display is not considered)
* Images added with text on top of them (and contrast is not sufficient to allow reading of text)
* Images are not compressed (and are very large)
* Images are too compressed (and are very pixelated). 

I think there are solutions to all of these issues. 

## Images used that add no value to the message the page is trying to communicate

Need to develop some sort of guidelines for imagery use. 

## Images added with text in them (which is not accessible or SEO friendly)

We need to provide an easy way to do this via code

## Images added with text on top of them (and mobile display is not considered) & Images added with text on top of them (and contrast is not sufficient to allow reading of text)

- Ensure that documentation for these components show both mobile and desktop implementations 
- Potentially templates need to provide quite a few options for positioning of text on images (eg. potentially top-left, top-right, top-center, bottom-right, bottom-left, bottom-center, center, center-left, center-right) in conjunction with media queries? 

- Ensure documentation makes it clear that only some images are appropriate for use in banners. For example, we need to find a way to discuss balance - eg. if you choose a busy picture (eg. students on the grass) you will need to minimise or forgo the use of text on this image. 

Another approach to this is the approach taken by Medium, which seems to be able to make a huge range of images work on their homepage. 

They also have an interesting convention for body images - they show the image without text to a point, but then fade it when text comes into view. 

- Provide easy testing via ODL and Browserstack

## Images are not compressed (and are very large), Images are too compressed (and are very pixelated), Images not suitable for retina
- Explain the use of tools like ImageOptim
- Create docs explaining image compression
- Create guidelines for the creation of retina ready images.

**Comment by waitingallday** [comment]
Can we move the top part of this to https://webhelp.staff.unimelb.edu.au

**Comment by sianglim** [comment]
@waitingallday I think this needs further discussion. It will take a while to convert Paul's notes into meaningful for the target audience and almost feels like we should be developing a digital content course (or a book!).

**Comment by waitingallday** [comment]
Going to close this now, since @herrweis is writing up a nice article covering these points
