### ISSUE TITLE
Sidebar search styles

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#203]
Hey Jason

Any chance we could get that sidebar search styles fix included?

```
.uomcontent #sitemap form.search {
  margin: 5px 0 10px 15px;
  max-width: 270px;
}

.uomcontent #sitemap fieldset .inline .search-button {
  margin-top: 5px;
}
```

**Comment by waitingallday** [comment]
Just to clarify, this was a small tweak to keep the search field implemented in the wordpress template from breaking at mobile widths - hopefully we can add the local search into more platforms soon.

![screen shot 2015-03-09 at 4 25 37 pm](https://cloud.githubusercontent.com/assets/863542/6550328/0a47556a-c679-11e4-9008-347e5b2d61e7.png)
