### ISSUE TITLE
disappearing checkbox on enquiry form

### ISSUE THREAD

**Issue by dcollett** [marcom-unimelb/unimelb-design-system#205]
https://web.unimelb.edu.au/components/enquiry
The checkbox next to "Subscribe to stay up to date with the latest news, events and information" has disappeared behind the text.

**Comment by waitingallday** [comment]
That is uncanny, I just updated the code sample for this!

Fixed in https://github.com/marcom-unimelb/unimelb-design-system/commit/b9a1296316de9553fe3616f41ac7f0b1c70e36cf

**Comment by dcollett** [comment]
We'll call it excellent service.

**Comment by waitingallday** [comment]
🍻
