### ISSUE TITLE
tab misbehaviour on window resize

### ISSUE THREAD

**Issue by dcollett** [marcom-unimelb/unimelb-design-system#212]
The responsiveness of the full width navigation tabs is a bit buggy. 

These examples use the tabbed-nav class. Example 1 is fine, but on example 2 if you resize the browser window things start misbehaving (see attached screen shot).

http://le.unimelb.edu.au/lss/room-search-1.html
http://le.unimelb.edu.au/lss/room-search-2.html

![screen shot 2015-03-13 at 11 41 54 am](https://cloud.githubusercontent.com/assets/1088483/6631174/fd2dd156-c975-11e4-959b-db54d2e35522.png)

**Comment by waitingallday** [comment]
We've updated the documentation recently, hoping to address this http://web.unimelb.edu.au/components/tabs - basically, keep the titles short and avoid using too many (I'm sure this occurred to you as well, looking at the example above!)
