### ISSUE TITLE
Side-menu: automated link to root URL

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#221]
In the side menu, the topmost link that shows the site name has its URL auto-inserted around it and is automatically set as the root of the URL.

This is problematic where sites are sitting in sub-folders i.e. - where the root URL is actually http://unimelb.edu.au/sitehome rather than http://unimelb.edu.au/ (see attached).

We need to either not auto-insert this value, or allow it to be overridden.
![screen shot 2015-03-24 at 9 58 02 am](https://cloud.githubusercontent.com/assets/924501/6792483/cff216d0-d20c-11e4-9d34-43d965ae4d92.png)

**Comment by waitingallday** [comment]
This can be done by adding a `data-absolute-root` attribute to the local nav div, eg.

```html
<div data-absolute-root="/sitehome" id="sitemap" role="navigation">
...
</div>
```

If you can control how this attribute is filled it can even use a relative url, as it does in the current graduate online site http://unimelb.edu.au/online

Will need to document this on http://web.unimelb.edu.au/articles/usage-instructions
