### ISSUE TITLE
Can't find the location from which to log a technical request re: CMS

### ISSUE THREAD

**Issue by jeremybean** [marcom-unimelb/unimelb-design-system#222]
Hello all - I came to web.unimelb looking for the location to log a ticket (I believe Zendesk is used?) for a user's permissions within the CMS to be re-adjusted.  Unfortunately there's no easily found link to (I eventually found it!) https://staff.unimelb.edu.au/services/it-support/web-help#/, a link which would make sense to me.

**Comment by waitingallday** [comment]
That's a good suggestion, I'll add that link to web.unimelb on the next update. Thanks Jeremy!
