### ISSUE TITLE
tables show 'undefined' when browser size is narrow

### ISSUE THREAD

**Issue by dkevey** [marcom-unimelb/unimelb-design-system#227]
tables are showing 'undefined' when browser size is reduced. Viewing this on MAC (not mobile). 
using templates v0.7

![tables_undefined](https://cloud.githubusercontent.com/assets/1305804/6820146/a7ea9fea-d31f-11e4-9fb7-33f24ed5a730.png)

**Comment by herrweis** [comment]
Confirmed in Firefox (not in Webkit nor Chrome though)
