### ISSUE TITLE
Can't access PhotoSwiped library on S3

### ISSUE THREAD

**Issue by sianglim** [marcom-unimelb/unimelb-design-system#229]
Hi @waitingallday,

I get an XML error when trying to access http://uom-templates.s3.amazonaws.com/templates/beta/photoSwipePackaged.min.js

This one works though:
//web.unimelb.edu.au/assets/photoSwipePackaged.min-211041f6e83d7a2f4de34c10bfa181d7.js

**Comment by neilang** [comment]
I can't see the file on the server. @waitingallday could it have been missed in the deploy?

**Comment by waitingallday** [comment]
Very likely, can you upload it direct to the bucket?

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Mar 25, 2015 at 6:12 PM -0700, "Neil Ang" <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't see the file on the server. @waitingallday<https://github.com/waitingallday> could it have been missed in the deploy?

**Comment by neilang** [comment]
Sure. Did you want it as a shared resource or bundled with the version?

**Comment by waitingallday** [comment]
It's referencing the beta version, that will do for now

**Comment by neilang** [comment]
The beta version is in the wrong bucket...

**Comment by waitingallday** [comment]
Fixed in https://github.com/marcom-unimelb/unimelb-design-system/commit/b7d9886c7913e9db3a6cb6b08e401b264ce7eba9
