### ISSUE TITLE
Matrix CMS Forms getting broken by DOM manipulation

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#231]
I've been developing a 404 page which includes a form that opens in a modal dialogue (Report this problem).
http://cms.unimelb.edu.au/error/404

Problem is, that DOM trickery moves the form contents to the modal, but not the enclosing form tags, so the form no longer works. Forms built in the CMS wrap the page contents in the form tag - not anything we can really do about that.

The same sort of thing happens even with this much simpler implementation: http://cms.unimelb.edu.au/error/404h
In this case, just wrapping the form in &lt;div role="main"&gt; breaks it.

**Comment by herrweis** [comment]
Cool! Should we combine the bespoke 404 (http://fvas.unimelb.edu.au/404) and the matrix one (I like Barry :-))? I really like the form (do we have any stats how often it is used?) so we could include that in the bespoke 404 as well?

**Comment by sianglim** [comment]
Also related, Oracle APEX application pages are also wrapped in form tags.

**Comment by woowoowoo** [comment]
Precisely, the fact that it's a 404 is irrelevant, and I already think I
have a workaround.
However, there are many applications which wrap content in form tags.
Also, forms in modals are fairly common.
This is going to continue to be a problem.

Andrew Harris
andrew@woowoowoo.com
http://www.woowoowoo.com

~~~ <*))))>< ~~~

On 1 April 2015 at 15:50, sianglim <notifications@github.com> wrote:

> Also related, Oracle APEX application pages are also wrapped in form tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcom-unimelb/unimelb-design-system/issues/231#issuecomment-88348635>
> .
>

**Comment by woowoowoo** [comment]
...and I know I'm going to sound like an old bore, but I'm not a fan of
Barry.
Cute, but I don't think the page offers the user clear options for
recovery/action.

Andrew Harris
andrew@woowoowoo.com
http://www.woowoowoo.com

~~~ <*))))>< ~~~

On 1 April 2015 at 15:53, Andrew Harris <andrew@woowoowoo.com> wrote:

> Precisely, the fact that it's a 404 is irrelevant, and I already think I
> have a workaround.
> However, there are many applications which wrap content in form tags.
> Also, forms in modals are fairly common.
> This is going to continue to be a problem.
>
> Andrew Harris
> andrew@woowoowoo.com
> http://www.woowoowoo.com
>
> ~~~ <*))))>< ~~~
>
> On 1 April 2015 at 15:50, sianglim <notifications@github.com> wrote:
>
>> Also related, Oracle APEX application pages are also wrapped in form tags.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/marcom-unimelb/unimelb-design-system/issues/231#issuecomment-88348635>
>> .
>>
>
>

**Comment by ptagell** [comment]
I think combining the two would be interesting. In my mind, 404 pages need to be both useful and entertaining (diffuse an otherwise frustrating situation).

**Comment by deanbrobinson** [comment]
This Smashing Mag article summarises it well:
http://www.smashingmagazine.com/2009/06/12/effective-maintenance-pages-examples-and-best-practices/

1. Keep your maintenance pages simple and useful
2. Realise it’s an inconvenience to your visitors
3. Don’t be afraid to use humour
4. Give your maintenance page the same look and feel as your regular site
5. Let visitors know when your site will be back
6. Provide recommended content
7. Invite your visitors to come back when the site is online again
8. Inform your visitors about the progress of the maintenance

**Comment by ptagell** [comment]
That's a great article. that. lets do that.

**Comment by waitingallday** [comment]
Ok closing this one!
