### ISSUE TITLE
Scholarship templates

### ISSUE THREAD

**Issue by sarahelucy** [marcom-unimelb/unimelb-design-system#236]
Arts has scholarship templates that we'd like to continue to use. At this point I'm wondering how to get the conversation started around this type of content and the best way to proceed with contributing scholarship templates to the WDS in the Matrix controlled environment. How far do we get into the design and development before the central team gets involved?

Are there other people out there that have scholarship templates? Here's an example of an Arts scholarship: http://arts.unimelb.edu.au/award/amy-gaye-cowper-tennent-memorial-scholarship and a scholarship listing: http://arts.unimelb.edu.au/scholarships

**Comment by waitingallday** [comment]
If you can construct the template from the components we have already, then the central team (Andi & me) won't need any involvement. I would definitely suggest discussing any design decisions with Andi though. Having said that, there are still plenty of areas in this system that we haven't covered yet!

Do you have anything to add @herrweis ?

**Comment by herrweis** [comment]
It's a great chance to see how contribution of page template works for someone outside the team. Do you feel that this would work for you @sarahelucy ? We could sit down together and give support if you need help.

And what @waitingallday said :-)

**Comment by ptagell** [comment]
There are a lot of scholarships listed here - http://services.unimelb.edu.au/scholarships 

Perhaps figuring out a template that works for both situations would be a good way to try to create something that is globally applicable (or more likely to be close).

**Comment by sarahelucy** [comment]
Thanks everyone, yes I'll try to think as big picture as possible so I'll be looking around for other examples too. 

I'll be do some moderated testing with a small group of students in the next few weeks so will hopefully get an indication of what's working and what isn't with current scholarship pages.

I'm thinking @herrweis, that based on student feedback, research into what else is out there and the pre-existing components and templates, I mock something up for us to discuss? Does that sound OK? I'd probably have something in about a month's time.

**Comment by herrweis** [comment]
:+1: Sounds good! Thank you!

**Comment by dkevey** [comment]
Hi Lucy, not sure if you are going into Squiz CMS, then I recommend that you look at using the Calendar asset and metadata schema to create the actual Scholarship. The benefit for this is that you can automatically show the scholarships that are open and accepting applications. 

Hopefully you can see this example in the CMS, of how this would work:
http://cms.unimelb.edu.au/fbetest/scholarships

This page is still a bit ugly (don't show Andi and Dean - it's really ugly), but you get the idea, of how the scholarship would show (automatically) when it's open. If you have loads, there would be an easy way to have a filtered list (of sorts).  

I'm using a standard page with jumpnav for the inside, but using the metadata and paintlayouts will ensure the headings etc and consistent across them all. It's also much easier for editors to update and manage.

![scholarships](https://cloud.githubusercontent.com/assets/1305804/7582964/69101472-f8d5-11e4-8a3d-8bc2c2232a5e.png)

![inside](https://cloud.githubusercontent.com/assets/1305804/7582968/6dd22e14-f8d5-11e4-9252-3443d5e2788c.png)

**Comment by sarahelucy** [comment]
Hi Donna, this looks rad. Yes, we'll be migrating our sites to the Matrix Controlled Environment. Your example is very similar to what I was thinking, although we would want to display the open and close dates on scholarships as well. We would also want to list closed scholarships the (assumed) benefit being that applicants might want to start planning early. Would your method work? Sorry, I haven't had a chance to look at how it actually works in Matrix, hopefully next week I'll have some time.

Ideally we would also use filtered listings at the top level so users could sort by eligibility. Arts has approx. 30 scholarships so a method for refining that list would be handy (We have also list about 100 merit based prizes that are automatically awarded. I'm not sure if there's much point in displaying these.)

Michelle Segal mentioned that you've been doing a lot of good work with Pursuit as well. Perhaps we can meet up with you in the next week or two and pick your Matrix brain?

**Comment by waitingallday** [comment]
Going to close this issue now, I will assume everything worked out :smile:
