### ISSUE TITLE
Allow links within pathfinder box

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#243]
Rather than forcing the whole pathfinder box to be a single link, it would be good to allow links within the box, particularly in the form of a list with individually linked list items. An example of this is the students.unimelb.edu.au site: http://students.unimelb.edu.au/explore

This could be solved by including a div inside the pathfinder, to achieve the same margins. For example:

<ul class="pathfinder-3">
    <li>
        <div>
            <strong> Title </strong>
            <ul class="inner-nav-list">
            <a href=""><li>Example link</li></a>
            <a href=""><li>Example link</li></a>
            </ul>
        </div>
    </li>
</ul>

**Comment by ptagell** [comment]
One thought is that perhaps the pathfinder isn't the right component to use in this case. 

@herrweis, correct me if I am wrong, but it is designed to be used when they are a very small number of highly important links, as opposed to a large number of medium priority links. Perhaps instead you should look at using the filtered list component with the pathfinder headings as filterable headings? 

Cheers
Paul

**Comment by dkevey** [comment]
Hey Camryn, I think Paul's suggestion of the filtered lists would work quite well, Tom and I have created asset listing's in the CMS to cater for this and I'm happy to help you try it.

**Comment by rothenburycam** [comment]
Interesting, okay - I will take a look at this.

**Comment by herrweis** [comment]
:+1:
