### ISSUE TITLE
header banner - cropping issue

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#245]
Hey - the header banners are now cropped

Last week the banners looked like this:
![header-old](https://cloud.githubusercontent.com/assets/1305804/7404082/6244fec2-ef21-11e4-97fc-bc8bb32797fa.png)

Now they are cropped like this:
![headers-new](https://cloud.githubusercontent.com/assets/1305804/7404097/a59fb5ae-ef21-11e4-89bb-8e6d82e1a99d.png)

**Comment by waitingallday** [comment]
This was introduced as a fix for IE flex box compatibility (it needs a fixed height container to align vertically), I'll try to make those calls more specific and fix this.

**Comment by dkevey** [comment]
ok - this was in Firefox.

**Comment by waitingallday** [comment]
I've put in a temporary fix, isolating the flex box changes to IE10 + 11 so all other browsers should be fine now. Will leave this one open until I can solve it for IE as well!

**Comment by waitingallday** [comment]
Okay I'm just going to close it now, not sure if this problem even still exists.
