### ISSUE TITLE
Unlock checklist not preventing access to link

### ISSUE THREAD

**Issue by chazbatrouney** [marcom-unimelb/unimelb-design-system#251]
`data-unlock-target` pointing to the ID of a link, to prevent access to that link until all items are ticked is not working causing link to remain available.
![screen shot 2015-05-06 at 11 04 21 am](https://cloud.githubusercontent.com/assets/640607/7485880/ad242f22-f3df-11e4-86a7-96898fd56284.png)

**Comment by waitingallday** [comment]
Looks like we fixed this one in [v3.6](https://github.com/marcom-unimelb/unimelb-design-system/releases/tag/v3.6)
