### ISSUE TITLE
page-header-tool div rendering white in IE9

### ISSUE THREAD

**Issue by FPG-Github** [marcom-unimelb/unimelb-design-system#256]
Have just hada  new computer delivered with standard MOE that runs IE9 and noticed that on the landing/home page banner, the page-header-tool div is rendering white: i.e. background-color rgb(255, 255, 255).

This means you get a big white box on the upper right hand side of the banner over the Search, Portals and Menu icons.

**Comment by waitingallday** [comment]
Wait- standard MOE runs IE9?? :smile: 

Can you attach a screen?

**Comment by FPG-Github** [comment]
Yup, IE9 – exciting isn’t it.

Attached: screen grab of landing page from web.unimelb.edu.au. Notice the fetching rendering of the white block in the top right corner – very cubist.
