### ISSUE TITLE
Style <p> and min-height in filtered list items 

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#259]
I'm using the following in filtered lists.

`<ul><li><strong>Title</strong><p>Paragraph<p></li></ul>`

- At the moment, the `<p>` appears too close to the `<strong>`. I think it would benefit from a small margin of 5px or so, just to improve readability.
- Also it would be handy to have a min-height value on the <li> (at the moment they default to about 110px - but if there was the option to have something between 170px - 200px, you could include slightly more information (ie 1 short descriptive sentence)

**Comment by waitingallday** [comment]
I think this is part of the larger discussion about how to display this content in a better way, as discussed in #266, so I'll close this one as a duplicate.
