### ISSUE TITLE
Add visual end point to the timeline component

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#262]
The line continues below the last point, which can give the perception that the timeline is ongoing. It would be good to add a narrow horizontal line or some sort of visual motif to represent the end of the timeline.

**Comment by waitingallday** [comment]
I agree, it's not really what I had in mind anyway - I was thinking more like

![screen shot 2015-05-18 at 3 05 13 pm](https://cloud.githubusercontent.com/assets/863542/7674620/76b5e5fe-fd6f-11e4-9142-ce6a0c014080.png)

Any thoughts @herrweis @deanrobinson ?

**Comment by deanbrobinson** [comment]
What you've proposed @waitingallday looks good to me. Clear and consistent.
