### ISSUE TITLE
Table doesn't show headers properly in small media query

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#264]
At the smallest media query, tables collapse removing the headers and force displaying 2 columns. The header for the column is displaying in the wrong cell (ie PhD candidate should be in the top cell, not the bottom cell). Also, the second header is not displaying at all.

![screen shot 2015-05-18 at 2 40 23 pm](https://cloud.githubusercontent.com/assets/11714609/7674491/77668380-fd6c-11e4-8c47-97ca136fcbf6.png)
![screen shot 2015-05-18 at 2 40 20 pm](https://cloud.githubusercontent.com/assets/11714609/7674492/77674cd4-fd6c-11e4-9ea4-f47602012c67.png)

**Comment by rothenburycam** [comment]
Also formatting 1 with borders and 1 without...?

**Comment by waitingallday** [comment]
Reported in #146
