### ISSUE TITLE
Jump nav sidebar highlights incorrect heading when last heading too close to bottom of page

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#265]
The jump nav sidebar changes active links to black when you are viewing that heading. However, it appears that if the last heading on the page is close to the bottom of the page, the previous link shows in black. I assume this is because the vertical scroll is still within the 'range' of the previous heading.

Eg: in this screenshot, I have clicked on "Expected course outcomes" but "What I can expect" is displayed as the active link/heading.

![screen shot 2015-05-19 at 3 07 50 pm](https://cloud.githubusercontent.com/assets/11714609/7695848/059cb6b6-fe39-11e4-9c4b-3ee413da72b5.png)

**Comment by waitingallday** [comment]
That's a tough one, the inpage nav can only change its current marker (the black link) based on where the document is scrolled to at the top of the viewport - with that window height, it will never be able to reach the last item. If you decrease the window height it should work as expected.

There's not really anything that can be done here, beyond adding some unnecessary padding below the page, or increasing the amount of content in that section?

**Comment by waitingallday** [comment]
Going to close this one for now, please re-open if you have anything more to add.
