### ISSUE TITLE
Tabbed navigation causes weird overlapping on certain elements

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#266]
Tabbed navigation is causing some weird overlapping - most notable in the filtered listing component and the jump nav (see my screenshot in #255). Strangely, when you resize the window, the jquery kicks in, neatly arranging everything in to place. On reload, it goes back to the overlapping, collapsed state. 

![screen shot 2015-05-26 at 4 56 57 pm](https://cloud.githubusercontent.com/assets/11714609/7806771/52bd48ae-03c8-11e5-86aa-cf1c97cf7b8f.png)

If you check the same content without it being nested under the tabbed navigation, it displays correctly. 

![screen shot 2015-05-26 at 4 57 04 pm](https://cloud.githubusercontent.com/assets/11714609/7806772/5396e000-03c8-11e5-870f-5fa5c9b79e3d.png)

**Comment by rothenburycam** [comment]
Happening across Chrome and Firefox and tested on a separate computer. Could be an issue with my site only as doesn't appear to be affecting the one @cigar69 is working on.

**Comment by waitingallday** [comment]
Not really sure about this one - we never tested a filtered listing under tabs, but I'll look into it today. On a related note there is way too much text in those boxes :smile:

**Comment by ptagell** [comment]
I think this probably makes a case for a new component. The filtered listing as it stands now with the coloured boxes is great when the items is easily identifiable (eg. course names), but if a description is needed then perhaps a new component is required where there is room to explain what the thing is about, but you can also filter. So the top half might remain, but the bottom half becomes more like a standard listing. 

Echoing @waitingallday the reason that these boxes can't have lots of text in them is that usability studies from course search revealed that this sort of listing doesn't work when 1) the boxes aren't sorted alphabetically (most of the time) and when 2) the boxes are different heights. 

Here's another example of where I don't feel like this component is working well - http://mspgh.unimelb.edu.au/research/research-priorities 

It does work well for course listings though, so it's just horses for courses. (LOL!). 

Thoughts / @herrweis

**Comment by deanbrobinson** [comment]
Cameron, it would be great to have a chat about this - it looks like the filtered listing component isn't quite right for what you're trying to achieve on this page. I'd also be interested to see what you've done so far using the new templates with your new site. Can I set up a time to meet?

**Comment by rothenburycam** [comment]
Hi Dean, yep I will PM you.

**Comment by rothenburycam** [comment]
Updating this thread: 

The issue only occurs when the top section of the filtered list section is present.

![screen shot 2015-05-27 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/11714609/7828698/5dd12e10-047a-11e5-9c8f-6e50b25447d2.png)

Once it's removed, it works fine the listings when under tabbed navigation.

![screen shot 2015-05-27 at 2 11 33 pm](https://cloud.githubusercontent.com/assets/11714609/7828697/5dd1203c-047a-11e5-9844-d004f7c6db26.png)

![screen shot 2015-05-27 at 2 11 08 pm](https://cloud.githubusercontent.com/assets/11714609/7828696/5dd11a60-047a-11e5-84cd-344fa3c3d1bb.png)


To clarify, the screenshot I posted yesterday was for illustrative purposes to show the glitching. I agree with @ptagell that a new component to facilitate descriptive text would be ideal. Keen to hear what @herrweis thinks about this being developed.

Screenshots in this post show what I'm really doing with the filtered listing, which was recommended by @ptagell in #243.

**Comment by herrweis** [comment]
You are right. All of you. At least partially :-) We might need a second filtered listing for very long lists with cryptic labels that need explanation. But I doubt that this will be helpful for users in each case. A huge amount of different bits of information is always hard (or even impossible) to digest, no matter what design is being used. In most cases it is better to restructure the content in smaller chunks.
However, I am happy to come up with new listing styles as soon as I get the data for a case where nothing else works!

**Comment by waitingallday** [comment]
I'm going to close this issue now, I think we may have fixed the root problem in a recent deploy (load order was causing a race condition)
