### ISSUE TITLE
Jumpnav behaviour fix

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#267]
Hi all

This is related to issues #266 and #255.

After discussing with @waitingallday it seems that the tabs use the same mechanism as the jumpnav which is causing the jumpnav to appear when there are H2 elements with anchor tags present in any of the tabs even if the <div class="jumpnav"></div> element isn't present (see https://github.com/marcom-unimelb/unimelb-design-system/issues/255#issuecomment-105392709).

Can we please update so H2 elements with anchor tags can be used in tabbed pages without causing this problem? Or fix it in some other way so this doesn't occur...

Thanks, Tom.

**Comment by waitingallday** [comment]
Can definitely fix this one. Thanks Tom!
