### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#269]
Just a quick one — the [getting started](http://web.unimelb.edu.au/getting-started) page has the sample code `<div class="no-js" id="navigation" role="navigation">` for the **local nav**, which, when implemented renders as shown below.

Judging by the rest of the codebase it looks like that should just be changed to `id="sitemap"`. 

![screen shot 2015-06-03 at 1 04 52 pm](https://cloud.githubusercontent.com/assets/6847023/7951935/3da19c2a-09f1-11e5-9cf2-de0e27782679.png)

**Comment by waitingallday** [comment]
That is really strange, I only used that markup very briefly. Will fix this, thanks!

**Comment by patpaev** [comment]
no worries!
