### ISSUE TITLE
Pathfinder's top padding disappears

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#273]
Pathfinder should have `padding-top: 3rem`, but if it is immediately following a `section.lead`, that padding seems to be overwritten by this rule:

<pre>.uomcontent .tabbed-nav [role="tabpanel"] section.lead+section, .uomcontent .tabbed-course [role="tabpanel"] section.lead+section {
  padding-top: 0;
}</pre>

example (see title almost flush with top of background image):
![screen shot 2015-06-03 at 4 47 54 pm](https://cloud.githubusercontent.com/assets/6847023/7954175/612c1f3e-0a10-11e5-8bc3-396d4065cee3.png)

(Might be worth noting that this happens within tabs.)

**Comment by waitingallday** [comment]
I'm going to close this issue - there has been a lot of work on the pathfinders but I'm not sure if we fixed this particular bug or not, feel free to reopen if it's still a problem!
