### ISSUE TITLE
Filter by Section dropdown box rendering in FireFox 31.5.3

### ISSUE THREAD

**Issue by FPG-Github** [marcom-unimelb/unimelb-design-system#277]
On filtered listing pages in FireFox 31.5.3 the Filter by Section dropdown box renders with both the styled format (white box and white double arrows) and the native grey drop down box. 
![filter by section box firefox 31 5 3](https://cloud.githubusercontent.com/assets/4566277/8123604/03f1bce6-1110-11e5-8251-a70e90bb08ab.PNG)

**Comment by kenpeter** [comment]
Firefox 38, win7
![firefox_38_win7](https://cloud.githubusercontent.com/assets/927150/8612533/6382dfb2-2715-11e5-9026-a3246f14f993.png)

Firefox 39, ubuntu
![firefox_39_ubuntu](https://cloud.githubusercontent.com/assets/927150/8612535/6cb1c472-2715-11e5-88c7-48a5623b6a06.png)

Solution:
Remove "-moz-appearance: window" in ".uomcontent .styled-select select { }" in uom.css
More detail: https://github.com/kenpeter/uom-design-system-comment/commit/fe297a1eed502fb086f0969d980b884009b48bd0

Shameless self-plug:
https://github.com/kenpeter/uom-design-system-comment
A project decompresses CSS and JavaScript of the unimelb-design-system. It allows me to understand JavaScript and CSS effectively. I also add lots of comments to the JavaScript part.
