### ISSUE TITLE
IE9 rendering Blue Boxes in different sizes compared to Chrome  & Firefox

### ISSUE THREAD

**Issue by cigar69** [marcom-unimelb/unimelb-design-system#279]
Not sure if this a browser bug or exceeding the characters limit for Blue Boxes for what is intended to be a quick jump-off point for the user.
IE example
![ie_capture](https://cloud.githubusercontent.com/assets/4565925/8199210/cbf1dea0-14f4-11e5-9d6e-fc44b8cab97a.JPG)

Same page in Chrome
![chrome_capture](https://cloud.githubusercontent.com/assets/4565925/8199227/044ee1da-14f5-11e5-84dc-7479c513194f.JPG)

**Comment by waitingallday** [comment]
This is one of the limitations of IE9, it will not support the technology we use on those boxes. To avoid this, you could reduce the text to 1-2 lines instead.

**Comment by herrweis** [comment]
Which version of IE?

I remember that this was deliberate on some (lower) versions of IE.

Generally you should not have too much text in these boxes, as it is hard to read and people are more unlikely of not clicking it (because of not reading)

**Comment by cigar69** [comment]
Thankyou

**Comment by cigar69** [comment]
IE 9

**Comment by waitingallday** [comment]
This is still in the same status, so I'm going to close the issue for now. We'll revisit it further down the track.
