### ISSUE TITLE
Enable .highlight-box p by adding padding-bottom:20px;

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#280]
Enable `<p>` elements inside `.highlight-box` by adding  `.highlight-box p { 20px padding-bottom;}`

This will allow us to highlight text that doesn't otherwise work in the `dl`, `dt`, `dd` elements.

Current use of `<p>`:
![screen shot 2015-06-19 at 11 29 40 am](https://cloud.githubusercontent.com/assets/11714609/8245746/96294532-1676-11e5-8ba3-a8ece4bdf028.png)

After adding padding:
![screen shot 2015-06-19 at 11 25 15 am](https://cloud.githubusercontent.com/assets/11714609/8245705/f3ea8cea-1675-11e5-958c-5b38ee1a65ef.png)

**Comment by axelboc** [comment]
@rothenburycam sorry for the delay - would a [notice](http://localhost:7001/components/notices) work instead? It's made specifically for single-line messages marked with a `<p>` tag.

```html
<p class="alert-info">
  <strong>Heads up!</strong> This alert needs your attention, but <a href="#">it&rsquo;s not super important</a>.
</p>
```

**Comment by axelboc** [comment]
@rothenburycam: closing this issue now - feel free to re-open it if the solution above doesn't work for you.
