### ISSUE TITLE
No favicon?

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/unimelb-design-system#282]
Are favicons (the little icon which appears in your tab) part of the design system? Or are they separate? Just noticed they don't appear in the CMS controlled environment, nor on web.unimelb.

Most sites using the design system template appear to have them - ie, MCM, VCA, FVAS, etc.

`<link rel="icon" href="demo_icon.gif" type="image/gif" sizes="16x16">`

![screen shot 2015-06-25 at 4 49 33 pm](https://cloud.githubusercontent.com/assets/11714609/8348774/3d95d03c-1b5a-11e5-9ac5-f310ed09a762.png)

I've raised this with Tom Stringer in case it's a CMS specific issue. I assume it needs to be added to the parse file that Tom's team maintains.

**Comment by waitingallday** [comment]
They're a separate thing, we should definitely add one to web.unimelb & the controlled environment as well.

**Comment by rothenburycam** [comment]
@tomstringer has kindly deployed this in the controlled environment. 🎅
