### ISSUE TITLE
Design system not rendering icons correctly in <footer class="cta">

### ISSUE THREAD

**Issue by FPG-Github** [marcom-unimelb/unimelb-design-system#284]
Design system not rendering icons correctly when used within the site footer specific addition footer class="cta".

Using the following code render big black icons (see attached: footer_class_cta_site-links.PNG)   

```
<footer class="cta">
	<ul class="site-links">
		<li><a href=""><svg class="icon" role="img"><use xlink:href="#icon-mail"></svg>Email</a></li>
	</ul>
</footer>
```

![footer_class_cta_site-links](https://cloud.githubusercontent.com/assets/4566277/8489842/44522a56-2163-11e5-8d03-2cb62f8a9527.PNG)

Also tried replacing the ul class "site-links" with "quicklinks" and that renders the icons white and proportioned correctly with the link text but the fount size of the whole list group is too small (see attached: footer_class_cta_quicklilnks.PNG).

![footer_class_cta_quicklilnks](https://cloud.githubusercontent.com/assets/4566277/8489857/8c70adc6-2163-11e5-9a95-76999a9c46cb.PNG)

Also can't see any documentation, but are there any specific components/class's that are to be used within the footer class="cta" section?

**Comment by rothenburycam** [comment]
I'm also experiencing issues with this, and have had to use the below code to make sure the layout works okay. My problem is more to do with the horizontal arrangement and the centering of the label text. 

`
.cta [data-icon] {
width:5.75em;
}
`

![screen shot 2015-09-14 at 2 13 23 pm](https://cloud.githubusercontent.com/assets/11714609/9841964/edd561ae-5aea-11e5-8767-fc7af42eaa8d.png)

Is it possible for some extra CSS for .cta element to be deployed in the next update?

**Comment by rothenburycam** [comment]
You can see the issue more clearly here with smaller icons. Having a wider width allows the text to center properly.

Current style:
![screen shot 2015-09-14 at 2 16 45 pm](https://cloud.githubusercontent.com/assets/11714609/9841989/51bd7742-5aeb-11e5-982f-3cca5e04dc82.png)

With wider width:
![screen shot 2015-09-14 at 2 16 54 pm](https://cloud.githubusercontent.com/assets/11714609/9841988/51bb9b16-5aeb-11e5-905a-353dc4d2943c.png)

**Comment by yevek** [comment]
Hi all, for sites that are in the Matrix Controlled Environment we will be implementing a standard footer shortly.

**Comment by rothenburycam** [comment]
Wonderful. Thanks Donna! :+1:

**Comment by waitingallday** [comment]
This should be ok now - the styles set on the icons documentation page will all filter through to the footers eg. `<span class="small" data-icon="student"></span>`
