### ISSUE TITLE
pathfinders + tabs +IE11

### ISSUE THREAD

**Issue by dcollett** [marcom-unimelb/unimelb-design-system#285]
Pathfinders under tabs in IE11 are overlapping. See:

http://fvas.unimelb.edu.au/
http://learningspaces.unimelb.edu.au/
http://mspgh.unimelb.edu.au/

I'm certain they used to work together until recently.

![screen shot 2015-07-09 at 2 30 32 pm](https://cloud.githubusercontent.com/assets/1088483/8587962/47d72e5e-2647-11e5-883d-1d662bf80338.png)

**Comment by dcollett** [comment]
Hi Jason, 
Do you have an ETA on a fix for this? I'm holding off making the http://learningspaces.unimelb.edu.au/ site live and have been asked for an update by the site owners.
cheers,
Dean

**Comment by waitingallday** [comment]
Hi Dean

Sorry, this should go out with the next deployment (really hoping to get it done this week).
