### ISSUE TITLE
Accordions in shared feature items

### ISSUE THREAD

**Issue by nejfone** [marcom-unimelb/unimelb-design-system#288]
If I use an accordion in a shared feature item, it generates a Javascript error. For example, I have used an accordion on the following page: http://eng.bespoke.unimelb.edu.au/study/degrees/master-energy-systems/apply-now?residency=domestic#nav

The first item opens, but subsequent items fail.

If I remove the class="accordion" from the parent ul tag, then the accordion functionality works but the CSS rules aren't applied:
http://eng.bespoke.unimelb.edu.au/study/degrees/master-energy-systems/apply-now?residency=international#nav

**Comment by waitingallday** [comment]
Hi, this seems to be a markup problem - the first item has a span title within the span title, and this is causing a JS error. We'll definitely want to prevent that in a future update, but for now could you try updating to the correct markup?

**Comment by nejfone** [comment]
Thanks. That's fixed it.
