### ISSUE TITLE
Request breadcrumb markup compatibility with schema.org

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#293]
Compatible breadcrumb markup results in richer results in Google.

We could render the markup as JSON, but if we're already rendering breadcrumbs on the page, it would be nicer to just make the markup compatible.

https://developers.google.com/structured-data/breadcrumbs
http://schema.org/BreadcrumbList

Not a biggy, just puttin' it out there :-)

**Comment by waitingallday** [comment]
This is already done in v3.0 (to be deployed this week)
