### ISSUE TITLE
in-page anchor links not working under tabs

### ISSUE THREAD

**Issue by dcollett** [marcom-unimelb/unimelb-design-system#296]
I'm migrating some pages out of Bespoke into a webfarm HTML site, using v1.0 of the design system.
 
Anchor links to content within the page aren't working: see this page, for example, under the apply now tab, the link "the form below":

http://www.unimelb.edu.au/online/ageing/masters/

Using v3.0 didn't help:

http://www.unimelb.edu.au/online/ageing/masters/index-v3.html

**Comment by waitingallday** [comment]
There's a lot of complicated mechanics going on with these tabbed pages, it basically needs to hijack the inpage anchors to operate the tabs (and side/inner tabs), and uses these as a URL to preselect the tab on page load. I believe this can be fixed, but it hasn't been planned yet - I could (and will) argue that linking someone off to another location within the page is a sign that there is too much content on the page. If the form is important at the top of the page, then it should probably go there.

**Comment by dcollett** [comment]
Thanks Jason. I’ll see if the site owners are willing to shift the form to the top of that section.

**Comment by waitingallday** [comment]
I'm going to close this issue - not sure if we fixed it or worked around it in the end, but feel free to reopen if it's still a problem.
