### ISSUE TITLE
Short Courses filter request

### ISSUE THREAD

**Issue by cigar69** [marcom-unimelb/unimelb-design-system#297]
Request to have the Short Course page set-up similar to Degree template layout.

Background
The Faculty of Medicine, Dentistry and Health Science has created a one-stop-shop for study. We feel the management and the discoverability of short courses for prospective students would be better facilitated if all the shorts courses for the MDHS were located within a central repository (similar to degrees).
http://mdhs.bespoke.unimelb.edu.au/degrees

However to increase discoverability of content by prospective students coming from various schools websites, we feel the Short Course page template could be further enhanced , if Shorts Courses on the landing page had the ability to be filtered by disciplines , again similar to Degree.
http://mdhs.bespoke.unimelb.edu.au/degrees

**Comment by neilang** [comment]
Hi Brendan,

We'll get someone to work on this. However, I will close this issue as it is related to the Bespoke project and not design system. The requirement has been captured in our internal tracking tool.

Cheers,

Neil
