### ISSUE TITLE
inline style for subscribe button

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#300]
Can you please create a style so that subscribe button is inline?
![subscribe](https://cloud.githubusercontent.com/assets/1305804/9482825/8f76e204-4bdb-11e5-8f37-950ad947ed93.png)

something like this?

![email](https://cloud.githubusercontent.com/assets/1305804/9482972/88d235c8-4bdd-11e5-83bf-5a249360fbea.png)

**Comment by ptagell** [comment]
Looks like this already exists in the design system v3. 

![screenshot 2015-08-26 10 36 14](https://cloud.githubusercontent.com/assets/150315/9483045/4ebfb710-4bde-11e5-995f-6b2bdb449373.png)

**Comment by ptagell** [comment]
We might just need to add an example to the design system @yevek - can you clarify @waitingallday ?

**Comment by herrweis** [comment]
this is unfortunately not fully implemented in v3 yet, I think

**Comment by ptagell** [comment]
Ok cool, I think it's a good inclusion though (obviously ;-) )

**Comment by herrweis** [comment]
+1

**Comment by waitingallday** [comment]
Yes definitely, there's a version on mercury and another we used for open day. Will add this ASAP.

**Comment by axelboc** [comment]
Fixed by PR #328
