### ISSUE TITLE
Jump-nav rendering in tabs where H2 headings have ids

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#302]
I discussed this a while back with Jason, so I know why it's there, but he suggested it should be logged as a bug so (finally) here it is.

The issue is that if someone is using H2's with ids inside a tabbed element, it creates the jump-nav sidebar, which breaks things.

Jason said:

jason [10:36 AM] 
http://fvas.unimelb.edu.au/study/courses/master-of-agricultural-sciences/degree-structure

jason [10:36 AM]
this is using the same code as the jumpnav, but it controls tabs within this tab

jason [10:36 AM]
overcomplicated :disappointed:

jason [10:37 AM]
i had never intended to allow the regular jumpnav to appear on tabs 

We can tell people not to do it, but it'd also be good if we could get it fixed so it wasn't an issue.

**Comment by waitingallday** [comment]
I think we already did this one :smile:  https://github.com/marcom-unimelb/unimelb-design-system/issues/267

**Comment by tomstringer** [comment]
Hmm. It's still being reported. Maybe because the Controlled Environment hasn't been updated to v3?

T.


On Aug 28, 2015, at 2:52 PM, Jason Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #302<https://github.com/marcom-unimelb/unimelb-design-system/issues/302>.

**Comment by waitingallday** [comment]
The fixes were tagged to 2.0, so I think you're right (2.0 became 3.0).
