### ISSUE TITLE
Staff listing inside modal

### ISSUE THREAD

**Issue by troymccann** [marcom-unimelb/unimelb-design-system#308]
If you put a detailed staff listing inside a model the image is left justified. A work around is to wrap the div in center tags.

```
<center><div class="frame"><img alt="Troy McCann" src="./assets/images/team/troy-mccann.png" /></div></center>
```

http://space.unimelb.edu.au/testing/team-and-partners

**Comment by waitingallday** [comment]
The modals are outside the style root that some of the staff listing is defined under, if you want it centered  please add ```class="center frame"``` on the div, don't use ```<center>``` tags!

**Comment by troymccann** [comment]
Thanks for the quick response!

I nested another div with the center frame class. It doesn't quite work like the center tag does, as poor form as it is to use them!

Click on the image of the Managing Director on the top of this page to see:
http://space.unimelb.edu.au/testing/team-and-partners

**Comment by waitingallday** [comment]
Oh yeah, sorry - could you try changing that element to a ```p``` instead of a ```div``` ? (p.center gets rid of that extra padding)

**Comment by troymccann** [comment]
Ah, yep, much better. Thanks for your help Jason!
