### ISSUE TITLE
Table alignment with the rest of the content

### ISSUE THREAD

**Issue by rahulj18** [marcom-unimelb/unimelb-design-system#323]
I am migrating the Law website using Matrix and one the pages I am using the table component (I try to avoid table as much as I can but in this instance plus couple of other places I need to use it)

![table design](https://cloud.githubusercontent.com/assets/3949786/9922908/7bbbf5d0-5d31-11e5-94d5-ee00733ed91f.png)

URL to the page - http://cms.unimelb.edu.au/controlled-environment/law/library/collections/rare-books-collection/rare-books-lectures/_nocache

As you can see that the table is not aligned with the rest of the components. Am I doing something wrong?

![code](https://cloud.githubusercontent.com/assets/3949786/9922973/54895024-5d32-11e5-984c-0c6315ce53ba.png)

**Comment by herrweis** [comment]
Hi @rahulj18, actually this is exactly how tables are supposed to behave — breaking out of the grid. Your case is a good example, because you have 4 columns with a lot of data which would not fit into the 700px content width. So it's not a bug, it's a feature.
