### ISSUE TITLE
Search button covers field in inline search forms

### ISSUE THREAD

**Issue by axelboc** [marcom-unimelb/unimelb-design-system#330]
PR #328 will introduce a new class for inline forms called `attached`, which solves this issue. The instances of the inline search form will need to be updated once the PR is merged.

**Comment by ptagell** [comment]
Just making sure we'll do a version bump of the design system if this will cause any breaking changes?

**Comment by axelboc** [comment]
Existing implementations won't break, but they won't get the fix unless they start using the new class.

**Comment by axelboc** [comment]
Hmm looks like the new `.inline.attached` markup doesn't *just work* for search forms: some `search-button` styles must be overridden. 

<img width="752" alt="screen shot 2015-11-09 at 11 20 58 am" src="https://cloud.githubusercontent.com/assets/2936402/11023682/feee5dd2-86d3-11e5-82a5-1b6ae7a9a201.png">

It might be easier and less confusing for users to introduce the new `attached` markup for search forms  as a breaking change. This would give us the opportunity to also drop the `search-button` class, thus avoiding the style overwrites.
