### ISSUE TITLE
should be able to nest checklist inside step list

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#331]
Andi says it's a bug. 

![lists](https://cloud.githubusercontent.com/assets/1305804/10009182/524e8c78-611c-11e5-8cc7-4b2e2eadf8f9.png)

![code](https://cloud.githubusercontent.com/assets/1305804/10009195/78c0a5ee-611c-11e5-9a43-95886ccf15c1.png)

**Comment by axelboc** [comment]
This is caused by the cascading of a `margin-left` style from the steps list. Will fix ASAP.
