### ISSUE TITLE
Search listing could handle image floats better

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#336]
In developing the WordPress theme, we've got a problem with tag/category listing pages, which are based on the search listing component. http://blogs.unimelb.edu.au/layout-test/category/parent/

The thumbnail is pulled from the post's 'featured image', which is used as a banner, so should generally comply to a landscape format, but it's probably not something we can rely on. As in the example, the floats can get a bit out of control.
![screen shot 2015-09-23 at 2 42 41 pm](https://cloud.githubusercontent.com/assets/848310/10038025/6e9ddd76-6201-11e5-9f05-3704df7f72f8.png)

BTW: We know the theme is unsatisfactory in the current state. Many unexplained problems and odd decisions. We're asking them to start again, and talk to us this time ;-) It looks like this is an issue regardless of their poor implementation.

And, yes, I know they're using the full size image as a thumbnail, we'll get them to use the generated 'small' version ;-)

**Comment by waitingallday** [comment]
Oh yeah definitely, this is a problem that will need to be fixed - it also occurs in http://web.unimelb.edu.au/components/news/ but can be managed carefully by ensuring an image height is not greater than the text beside it. Not ideal, but we will come back to this.
