### ISSUE TITLE
Openstreetmap implementation appears to be broken

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#337]
I'm seeing a blank, grey map here.
http://web.unimelb.edu.au/components/maps/#openstreetmap

**Comment by waitingallday** [comment]
Just coming back to this now - I used the default tileset from leaflet (mapbox), and it seems that they've updated to a new version. Ideally we should be using a more stable set (ie. our own), but I'll update to the new mapbox set for now.

**Comment by waitingallday** [comment]
There's an easy fix to this, but we really ought to use our own tileset from mapbox with its own access token. Will come back to this!
