### ISSUE TITLE
Detailed Staff listing don’t place images correctly with long descriptions

### ISSUE THREAD

**Issue by FPG-Github** [marcom-unimelb/unimelb-design-system#340]
Images in Detailed Staff Listings don’t display correctly if you add a longer job description or title to the listing. The circular images don’t centre and the diamond images lose their shape.
![staff listings](https://cloud.githubusercontent.com/assets/4566277/10127762/c4d1b608-65ea-11e5-89a9-7530fee7ed50.PNG)

**Comment by herrweis** [comment]
Hi @FPG-Github,

this is a bug we will fix as soon as possible, but in the meantime you could use <br> to break up the line if you have to use a lot of text in this field.

Cheers,

Andi
