### ISSUE TITLE
Glitch in the 'jump navigation'

### ISSUE THREAD

**Issue by arts-unimelb** [marcom-unimelb/unimelb-design-system#341]
Just come across a glitch in the 'jump navigation' on the new CMS

https://cms.unimelb.edu.au/controlled-environment/arts/current-students/undergraduate/diploma-in-languages

https://cms.unimelb.edu.au/controlled-environment/arts/current-students/undergraduate/peer-assisted-study-sessions 

When you click on the jump links at left, the one above where you want to go to is being highlighted. This is happening on several pages. I have checked the code and there is nothing wrong there.

I DON'T THINK IT'S RELATED TO THE LENGTH OF THE PAGE ISSUE THAT WAS PREVIOUSLY REPORTED.

Thank you!
Marcus

**Comment by waitingallday** [comment]
I believe this one was fixed in a deploy made in the past week or two, sorry for not getting back to you sooner!
