### ISSUE TITLE
Refactor .short header styles/injection

### ISSUE THREAD

**Issue by sianglim** [marcom-unimelb/unimelb-design-system#347]
Discuss with @waitingallday about the following:

* background-image should be removed from the `intranet/_short_header.scss` file
* The injection needs to allow a `background-image` inline style for the header
* `intranet/_short_header.scss` should probably be moved into `injection/header/index.scss`

**Comment by axelboc** [comment]
Fixed with PR #359

**Comment by axelboc** [comment]
Fixed by #359
