### ISSUE TITLE
CSS: style request - .citation 

### ISSUE THREAD

**Issue by tblundell** [marcom-unimelb/unimelb-design-system#375]
Hi,
Im wondering if a custom class could be added as part of the design system stylesheet.   

Currently I'm adding a small bit of custom CSS to my pages for wrapping text (in this case 'citations') around a block element. 
My style is based on the '< code >' styling. Unfortunately I can't use '< code >' due to the content overflow (hidden text longer than the area width). 

See the image and code below:

<img width="711" alt="screen shot 2015-10-16 at 3 31 35 pm" src="https://cloud.githubusercontent.com/assets/943446/10533895/3a1d80c0-741b-11e5-9474-4f7ebc475ba6.png">

.citation {
background:#f1f1f1;
border:#e4e4e4 1px solid;
padding:15px;
font-family: 'Courier New', Courier, fixed;
margin-bottom:1em;
}

**Comment by axelboc** [comment]
This probably needs a designer's input? @herrweis

**Comment by yevek** [comment]
Hi @axelboc and @herrweis  just following up on this one - we have a large chunk of content to migrate into CMS and need a style like this added as well please.

**Comment by waitingallday** [comment]
Fixed by #442 - example will be available on http://web.unimelb.edu.au/components/text/ when deploy goes live
