### ISSUE TITLE
OpenStreetMap has incorrect attribution

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#387]
Been meaning to point this minor issue out...

OpenStreetMap ask that you use the attribution: "© OpenStreetMap contributors", linked to: https://www.openstreetmap.org/copyright, as per the example on that page.

Mapbox have their own way of doing it: https://www.mapbox.com/mapbox.js/example/v1.0.0/, which is presumably deemed adequate.

**Comment by waitingallday** [comment]
I picked that line up from the leaflet quick start guide, but I just noticed now they've changed the link on their homepage example to go to the copyright page now. Will update this, thanks Andrew.
