### ISSUE TITLE
Styling the meta menu

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#389]
Very minor styling point.

On the site: http://blogs.unimelb.edu.au/qtraslate-test/ (use the simple password 'doc' to log in) I implemented a language switcher in the meta menu, which leads to a sub-meta menu - all seems to work fine.
I just felt that the space between the top of that menu, and the 'return' link was a bit uncomfortably tight (see image).

Like I said… very minor ;-)

![image](https://cloud.githubusercontent.com/assets/848310/10625635/f8633d3a-77f0-11e5-8ec8-b1aa1b0f96a3.png)

**Comment by axelboc** [comment]
@woowoowoo: is this still an issue? The spacing seems to be fine now unless I'm mistaken.

**Comment by woowoowoo** [comment]
no, was a problem with the implementation in wordpress - thanks
