### ISSUE TITLE
Injection contains link to a 404

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#390]
The 'Browse the University' link injected into menus links to a non-existent page: http://www.unimelb.edu.au/sitemap

Not a problem if your click is hijacked by javascript as intended, but if something breaks the design system, the link - and the 404 - is exposed.

**Comment by waitingallday** [comment]
Oh yeah, definitely - @ptagell we should get this page set up as a static one-pager with the contents of the global nav (I believe that was the original plan).

**Comment by ptagell** [comment]
wow. Yep. Lets do it.

**Comment by waitingallday** [comment]
I have this page ready to go, just waiting on some style fixes in the next deploy.

**Comment by waitingallday** [comment]
Clearing the milestone, this will need to go up post-deploy

**Comment by waitingallday** [comment]
Page is now published, it literally took two entire releases to get this page working :smile:

**Comment by axelboc** [comment]
The link still opens the sitemap menu instead of the sitemap page. I'll change this now.
