### ISSUE TITLE
Document that it is not a good idea to put people's faces into heading images (unless a profile page)

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#41]
Also might be worth noting that subjects that require lots of focus should be along the top of the image. 
![screen shot 2014-03-28 at 12 12 19 pm](https://cloud.githubusercontent.com/assets/150315/2545414/1534503c-b616-11e3-859e-f4981dc88f85.png)
![screen shot 2014-03-28 at 12 12 14 pm](https://cloud.githubusercontent.com/assets/150315/2545415/153ad808-b616-11e3-8d97-cea94ad359d7.png)

**Comment by waitingallday** [comment]
Can we move this to https://webhelp.staff.unimelb.edu.au

**Comment by sianglim** [comment]
I've put up a modified version of this on Zendesk. It's now live:
https://webhelp.staff.unimelb.edu.au/hc/en-gb/articles/204758037
