### ISSUE TITLE
Image alignment issue in article

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#427]
This message from Marnie, at International House.

Hi Andrew,

We are loving our new website. 

What code can I use for an image caption in a news item? I tried to use the code from 'figures floating' but then spacing of the entire article shifted to the right, making it look a little skewed  - http://ihouse.unimelb.edu.au/home/celebrating-a-decade-of-vmial-psa-medical-and-dental-scholarships/

Thanks for your help.

**Comment by waitingallday** [comment]
That layout was never intended to have inset images, and I'm not sure it should on this page. The inset image is calculated without respect to the meta aside, so even if the padding is fixed the image will potentially be dragged out of the viewport.

Anyway, to get it unbroken remove the `with-figure` from the section, and wrap the figure in a `<div class="with-figure">` - that class has styles that are interfering with the left padding, but will leave the container alone.

**Comment by axelboc** [comment]
I was thinking she should use `<figure class="full-width">` so that it's in the flow of the article. Just need to add a max-width in the news component.

**Comment by woowoowoo** [comment]
Thanks, Jason's suggestion will get her through for now.

**Comment by axelboc** [comment]
I've implemented the `full-width` solution. It's probably a good thing to have in the future.

**Comment by waitingallday** [comment]
Yeah true, good thinking!
