### ISSUE TITLE
Lock icon required for search.unimelb

### ISSUE THREAD

**Issue by chazbatrouney** [marcom-unimelb/unimelb-design-system#430]

**Comment by chazbatrouney** [comment]
https://www.google.com/design/icons/#ic_lock

is a required icon so authenticated search results can be identified in the listing.  I will then work with @axelboc to modify the search layout to include this icon as show in the attached mock up:
![search-inside-uom-whitelist](https://cloud.githubusercontent.com/assets/640607/10984759/db032562-846f-11e5-83b1-744f7dc4ac50.png)

**Comment by herrweis** [comment]
Good idea. May I suggest a small change?
![search_lock](https://cloud.githubusercontent.com/assets/2480825/10984909/0858e172-8471-11e5-8574-85ed34455e74.jpg)

**Comment by chazbatrouney** [comment]
Of course you can @herrweis and in fact, I am happy for you to contribute this icon inclusion on one of the existing search layouts on web.unimelb.edu.au/layouts/search

**Comment by herrweis** [comment]
@chazbatrouney This was just a quick suggestion. I don't have time or resources to do this now.
