### ISSUE TITLE
Please update the Facebook icon in the footer of all pages to the correct logo

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#435]
This came in as a Zendesk ticket:

Laura Sullivan Friday 11:15
Please update the Facebook icon in the footer of all pages to the correct logo (f in a box, rather than f on its own)
url: pursuit.unimelb / mdhs.unimelb / all new format pages

+++

She has a point.
Correct usage is with the box
https://www.facebookbrand.com/

**Comment by waitingallday** [comment]
@herrweis ?
