### ISSUE TITLE
please change the link for facebook in the footer of every page

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#436]
Another ticket via zendesk:
Laura Sullivan <laura.sullivan@unimelb.edu.au>

All Unimelb pages - please change the link for facebook in the footer of every page and any other instance that it is referenced 
From: https://www.facebook.com/melbuni 
To: https://www.facebook.com/unimelb

**Comment by waitingallday** [comment]
The design system already uses this link (it was updated at Yves' request). Have logged an issue with the old global templates https://github.com/marcom-unimelb/wbg-templates/issues/102
