### ISSUE TITLE
.localnav breaks page design with headerless class

### ISSUE THREAD

**Issue by chazbatrouney** [marcom-unimelb/unimelb-design-system#459]
When using the `jumpnav` class, it breaks the layout of a page using the `headerless` class, causing:
- main content to be pushed up the page
- headerless blue line to vanish (replaced with standard shadow)

Screen shot (`.jumpnav` omitted)
![screen shot 2015-11-17 at 10 26 04 am](https://cloud.githubusercontent.com/assets/640607/11198077/12d8e0ea-8d16-11e5-8bc6-57a01ea9defa.png)

Screen shot (`.jumpnav` included)
![screen shot 2015-11-17 at 10 26 17 am](https://cloud.githubusercontent.com/assets/640607/11198088/20e4b54c-8d16-11e5-9f2b-ab1013960bdb.png)

**Comment by waitingallday** [comment]
Web.unimelb is using this now? eg. http://web.unimelb.edu.au/components/accordion/

**Comment by chazbatrouney** [comment]
That is weird as it seems to render correctly there apart from this problem:
![screen shot 2015-11-17 at 10 42 24 am](https://cloud.githubusercontent.com/assets/640607/11198312/0b7b1046-8d18-11e5-9e1b-102adf73fc32.png)
