### ISSUE TITLE
headerless inconsistencies

### ISSUE THREAD

**Issue by chazbatrouney** [marcom-unimelb/unimelb-design-system#465]
Currently there are methods for implementing the headerless style:

1. set the headerless class on container role="main"
2. use empty div as first child:
```
<div role="main">
 <div class="headerless"></div>
 ...
</div>
```

There are design inconsistencies with each of these methods and need to be standardised.  I would also suggest removing option 1 as Staff Hub and web.unimelb are the only ones really using the style and it would be better to have one method.

Corrected behaviour of style is to replace the shadow hr below the menu/header with the solid blue hr.  This is not happening when method 2 is used in conjunction with the `.jumpnav` class, as per this screen grab:
![screen shot 2015-11-17 at 1 30 57 pm](https://cloud.githubusercontent.com/assets/640607/11201330/42e6de70-8d31-11e5-81cb-50a4f2470635.png)

Correct behaviour should be (apart from the issue outlining the `jumpnav` being covered by the logo when at top of screen):
![screen shot 2015-11-17 at 1 34 03 pm](https://cloud.githubusercontent.com/assets/640607/11201335/4fd6a4ee-8d31-11e5-9855-6aab94ea117d.png)

**Comment by waitingallday** [comment]
Both headerless styles are undocumented at the moment, the 1. you're referring to was only a test on the UI prototypes. The 2nd method was built to accommodate matrix, and works better with the jumpnav anyway - Nav above the line is the correct behaviour. There is a fix on master for the padding below the logo that will go out in the next deploy.

**Comment by axelboc** [comment]
Turns out that both behaviours (blue line above or below the nav) can be obtained by simply swapping the two divs in the markup. However, the blue line below the nav looks best when an aside is present:

<img width="894" alt="screen shot 2015-11-17 at 2 51 29 pm" src="https://cloud.githubusercontent.com/assets/2936402/11202294/bc4ce152-8d3a-11e5-8fdc-eb1d9ef4e7e1.png">

**Comment by waitingallday** [comment]
Yeah- not sure what the correct behaviour is, to be honest. @herrweis ?

**Comment by axelboc** [comment]
FYI, there's now a top-only version of the jumpnav (#466: `<div class="jumpnav top"></div>`), which might influence the decision. In this case, I feel like the border above would look better.

<img width="1418" alt="screen shot 2015-11-17 at 3 28 35 pm" src="https://cloud.githubusercontent.com/assets/2936402/11202768/e701494c-8d3f-11e5-8da4-d753836a00f3.png">

**Comment by herrweis** [comment]
Yes the border should be always above (as a divider)

**Comment by chazbatrouney** [comment]
@herrweis are you also recommending that the class of `aligned-title` be used for all pages that use the `headerless` layout?
