### ISSUE TITLE
Minor checkbox styling problem

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#470]
The default wordpress comment form has a problem displaying a checkbox.

Below the submit button on the comment form:
http://blogs.unimelb.edu.au/layout-test/2015/10/28/a-simple-standard-post/#respond
is a checkbox for notifications, but because the label has no child span, it's displaying incorrectly.
Any chance the styling could be altered so that the span is not required?

**Comment by axelboc** [comment]
It's doable I reckon. Might be a breaking change, though. Adding this to the `next-major`milestone.

**Comment by waitingallday** [comment]
I'd like to spend some time and refine that comment block a bit too, it's pretty unwieldy at the moment - I'm sure we can come up with something a bit more compact

**Comment by tomstringer** [comment]
Adding another vote on this one, but for Matrix.

See "Question 6" here: https://cms.unimelb.edu.au/controlled-environment/testing/feedback2 

Similar problem.

**Comment by woowoowoo** [comment]
Referring back to this issue. It's not going away, and it applies equally to radio buttons.
We are seeing a repeating pattern where site owners are 'hacking' their forms to get around the issue - leading to the inevitable problems. It's not restricted to Matrix, or WordPress (and plugins), though that's where we're seeing the biggest issues.
If it's going to be a 'breaking' change and delayed because of that, then, at the very least, it would be nice to be able to turn off the design system styling using a class on radio buttons/checkboxes or a parent container. Default styling would be a little ugly, but it would work.

**Comment by waitingallday** [comment]
I'm going to look into this next! Sorry it's taken so long, we had intended to fix this in the next major version (breaking change), but I'll see if we can arrange an override until that one is ready.

**Comment by woowoowoo** [comment]
heh, no problem ;-)

Andrew Harris
andrew@woowoowoo.com
http://www.woowoowoo.com

~~~ <*))))>< ~~~

On 2 March 2016 at 15:41, Jason Smith <notifications@github.com> wrote:

> I'm going to look into this next! Sorry it's taken so long, we had
> intended to fix this in the next major version (breaking change), but I'll
> see if we can arrange an override until that one is ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcom-unimelb/unimelb-design-system/issues/470#issuecomment-191057371>
> .
>
