### ISSUE TITLE
Query re. use of selects in staff hub and accessibility. 

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#489]
From: Albert Penticoss [pena@unimelb.edu.au]

I’m very surprised to see the used of select drop down for links on the new staff hub homepage.

As far as I’m aware this is a accessibility no-no. Form elements are for forms not for links. In my experience observing screen reader users, they use search of links (a tags) to quickly find link throughs. They will not ‘see’ these links hidden inside a select box. Semantics are important. Same look and feel can easily be achieved with a list of links and some javascript to show/hide (using proper hide css that hides visually but not from screen readers).

Albert John Penticoss

**Comment by axelboc** [comment]
It did cross my mind too. You're right for the case when a screen reader user searches the page for links. However, if the user is just tabbing/reading through with the keyboard, the drop-downs will work fine. I think the issue is mitigated by the fact that those are just shortcuts. If the user doesn't know about the drop-down menus, then he/she will just navigate to those section-map pages and find the sub-page they're looking for.

**Comment by iPadisthin** [comment]
Yeah but screen reader users rarely tab through pages, its too slow. They might do so the first time they visit a page, even so they are unlikely to consider a form element to not be a form - semantics aids them.

Second point is fair enough, if that's the design rationale that went into the design, if its an after thought then that's just luck. But why not give them same quick access as everyone else by providing links.

Form element is being used here for style purposes.

**Comment by axelboc** [comment]
This page provides an alternative worth looking into, I think (a typical navigation menu with proper anchors, which opens on `:focus` and `:hover`). http://uxmovement.com/forms/stop-misusing-select-menus/

**Comment by axelboc** [comment]
There's been more discussions about this before the holidays with @waitingallday and @anormand. An accessible drop-down navigation menu is being developed for use on the Staff Hub homepage and in the breadcrumbs on mobile: #497
