### ISSUE TITLE
Visual look of jump nav with long headings on small screens

### ISSUE THREAD

**Issue by sianglim** [marcom-unimelb/unimelb-design-system#502]
A mixture of long and short headings make the current two-column layout a bit hard to read.

![screen shot 2015-12-17 at 2 32 17 pm](https://cloud.githubusercontent.com/assets/1217045/11860741/169b59ba-a4cc-11e5-9fb1-3a5b323d08ac.png)

**Comment by axelboc** [comment]
FYI, the CSS column layout allows the items to stack vertically first, which solves the spacing issue mentioned above and is more logical for the user than the current left-to-right-then-top-to-bottom order. The new layout also adds a gutter between the two columns.
