### ISSUE TITLE
Accordion plus/cross buttons don't work

### ISSUE THREAD

**Issue by dasithds** [marcom-unimelb/unimelb-design-system#522]
Hey guys, I've attached a screencast regarding the bug.

[2016-01-20_1338.swf.zip](https://github.com/marcom-unimelb/unimelb-design-system/files/96886/2016-01-20_1338.swf.zip)

**Comment by axelboc** [comment]
Hi and welcome to GitHub! :wave: 

Thanks for reporting this issue, but I'm afraid none of us can play SWF files on our machines. A simple textual description with a couple of screenshots is usually easier for us to deal with.

However, in this case, we might know what the issue is about: are you trying to click on the plus icon and the accordion doesn't open? We've been meaning to fix that for a while, but haven't got around to it yet, so thanks for making the issue official :+1:

**Comment by dasithds** [comment]
Hey Axel!

Oh sorry, did not know that y'all preferred screenshots and text. By the
way, you can open the SWF in the browser and that should work.

The issue we have is the "+" sign and "x" sign on the left do not do
anything. Also, when we open an accordion item that is very long and open a
shorter accordion item below it, the screen jumps to the bottom of the
browser. Also the accordion behaves differently in Chrome and Firefox
(clicking on items tend to make the screen jump to the bottom of the page
and not to the title of the newly open item.)

Also, in the Single Block Open accordion, there is no way to have all the
items closed once we open the first item, we can only close the item by
opening a different item.

Thanks a lot!
Dasith.

**Comment by axelboc** [comment]
Okay, we'll try to work on that. Thanks for the feedback!

P.S.: we don't have have the Flash Player plugin installed in our browsers any more - very few websites require it nowadays and we like to avoid those that still do :D

**Comment by dasithds** [comment]
Hey Axel,

Thanks! Appreciate it! Oh ok, I guess HTML5 is the future, huh?

Alright, I'll let the stakeholders know your on the case.

Regards,
D.

**Comment by axelboc** [comment]
Adding one more issue to the list: when a content panel is really big, the footer gets taller in Chrome.

<img width="1414" alt="screen shot 2016-02-01 at 4 46 39 pm" src="https://cloud.githubusercontent.com/assets/2936402/12709778/66e2eff4-c903-11e5-9201-750113f39dd2.png">

**Comment by axelboc** [comment]
Recap:

- The clickable area of the headings doesn't include the icons.
- In a single-block-open accordion, if the opened section is very long and a shorter section below it is clicked, the height of the page decreases significantly and the page jumps to the footer.
- In a single-block-open accordion, there is no way to close a section.
- In Chrome, a hidden panel with lots of content makes the footer expand (i.e. `max-height: 0;` is not enough).

**Comment by axelboc** [comment]
The additional issues mentioned have been moved to separate issues: #532, #533
