### ISSUE TITLE
Multiple pins on map

### ISSUE THREAD

**Issue by spacetj** [marcom-unimelb/unimelb-design-system#524]
Hey guys,

I was wondering if its possible to make a map components where we can have multiple pins. That would be super convenient as I'm trying to display a service that's available in different parts of the university.

Appreciate your work and time

Cheers,
Tejas

**Comment by axelboc** [comment]
I'm on it!

**Comment by axelboc** [comment]
Okay, this will be in the next minor release. You'll just need to separate the pairs of coordinates with pipes (`|`) inside the `data-pin` attribute.

**Comment by spacetj** [comment]
Awesome, thanks Axel. Just to confirm, will this only work with gmaps? Or is it going to work with the open street maps as well? Thank you for your time.

**Comment by axelboc** [comment]
It will work with OpenStreetMap as well :-)
