### ISSUE TITLE
Unexpected scrolling when selecting tab via URL hash

### ISSUE THREAD

**Issue by axelboc** [marcom-unimelb/unimelb-design-system#528]
When selecting a tab via the URL, the browser tries to scroll down to the tab's panel before JS has time to hide the other panels. As a result, it scrolls too far down - e.g. http://web.unimelb.edu.au/layouts/course#course-structure-2

**Comment by woowoowoo** [comment]
Just received a Remedy ticket for this. INC000001652347.

Occurs most noticeably in Firefox (I'm running 46.0.1), where loading a direct URL - eg: http://engagement.unimelb.edu.au/#international just displays the page footer.

**Comment by waitingallday** [comment]
I've got a fix ready for this, will deploy in v4.2 tomorrow.
