### ISSUE TITLE
Blue alerts/flash notifications are slightly off vertical centre. 

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#529]
Is it possible to move these down a little so they are centred? Not sure if this is a design system issue or pursuit, so putting it here. 

![screenshot 2016-02-02 12 02 45](https://cloud.githubusercontent.com/assets/150315/12736526/18732bac-c9a5-11e5-8b85-f88763377866.png)

**Comment by axelboc** [comment]
Yeah, I created a flash message component a couple of weeks ago: #518. It should go in the next release.
