### ISSUE TITLE
Image header "blurred" 

### ISSUE THREAD

**Issue by tblundell** [marcom-unimelb/unimelb-design-system#542]
When using IMAGE HEADER MID ALIGN ENHANCED the div surrounding the header text renders as hard edged block. Contrast wise the text pops more using the '.blurred' class <div class="mid-align blurred"> but the edges of the div block aren't displaying as 'blurred' - but more a semi-transparent stripe across the image. The hard edge is noticeable on lighter images.  

The box-shadow "spread" property is 71px. Played quickly and upping it to something like 135px softens it up. 

see: http://web.unimelb.edu.au/components/headers/#image-header-mid-align-enhanced

![screen shot 2016-02-16 at 2 28 22 pm](https://cloud.githubusercontent.com/assets/943446/13066522/f902d38c-d4ba-11e5-8189-f048b01d3d70.png)

![screen shot 2016-02-16 at 2 40 36 pm](https://cloud.githubusercontent.com/assets/943446/13066544/4b25dbc8-d4bb-11e5-817b-762c60fcf61c.png)

Tested on MAC, Safari & firefox

**Comment by waitingallday** [comment]
I had noticed that, it works fine in Chrome but not in Safari or FF. There is a custom fix for this on pursuit, but I haven't had a chance to migrate it back to design system yet. Thanks for the reminder!

**Comment by tblundell** [comment]
awesome. i won't add a local hack then :)

**Comment by axelboc** [comment]
@waitingallday - the homepage of Pursuit seems to have the same issue. The article pages are fine, though, as you said.

**Comment by axelboc** [comment]
Would it make sense to move the blurred class to the banner and have a pseudo-element cover the whole background image with a linear gradient?

**Comment by waitingallday** [comment]
I think we already have one that does that - I believe the purpose of this style was to hug the text in a white title to improve contrast against a light image @herrweis ?
