### ISSUE TITLE
Degree structure - example plans on Bespoke

### ISSUE THREAD

**Issue by lucyliu123** [marcom-unimelb/unimelb-design-system#546]
Hello,

For the degree structure page for the Degree Programs, can subjects indicate type without opening I.e. By symbol or colour? Like on the old bespoke cms. 

![degree structure plan](https://cloud.githubusercontent.com/assets/17328478/13165735/96032258-d714-11e5-8487-d39332129493.png)

**Comment by ptagell** [comment]
Potentially you just need to add in more sections - eg. instead of Year 1, it's Year 1 semester One. then you could also group by "core" "elective" etc

**Comment by waitingallday** [comment]
Hi Lucy,

This is more of an issue with bespoke rather than the design system - we have no specific way of showing this at the moment, but I believe it has been reported as an issue. You could try asking on the bespoke slack group?

**Comment by lucyliu123** [comment]
alright, thanks for the suggestions :)

**Comment by waitingallday** [comment]
No problem, I'll close this for now - it may end up being solved in design system, but will require some work on the bespoke end to set this up.
