### ISSUE TITLE
Bespoke features not formatted properly

### ISSUE THREAD

**Issue by dasithds** [marcom-unimelb/unimelb-design-system#547]
Hi guys,

In the new version of the bespoke CMS, I cannot get multiple features to display within the same row. If you look at the attached image, there are three rows of features under a single column. It should be one row with three columns with each feature getting its own column.

I just wanted to bring this up and ask whether it was a bug or something to be implemented soon.

Thanks!
D.
![2016-02-19_1428](https://cloud.githubusercontent.com/assets/16767361/13165849/994c15a4-d715-11e5-957d-5305854e1c41.png)

**Comment by waitingallday** [comment]
Hi,

This issue list is only for the design system, you'll need to contact the bespoke maintainers if you have an issue with that system.

**Comment by dasithds** [comment]
Woops! Sorry!

**Comment by waitingallday** [comment]
No problem!
