### ISSUE TITLE
Enhancement - Sort tables by column

### ISSUE THREAD

**Issue by dasithds** [marcom-unimelb/unimelb-design-system#548]
Hey guys,

I would like to request some new functionality on behalf of the stakeholder(s.) They would like to sort a table by column. For example, being able to sort this table by scholarship name, school or study area etc...

Thanks,
D.
![2016-02-19_1434](https://cloud.githubusercontent.com/assets/16767361/13166052/96b7e348-d717-11e5-9022-a2c4cccd3baa.png)

**Comment by waitingallday** [comment]
I think that's a good idea, and I'm surprised no one has requested it earlier!

**Comment by dasithds** [comment]
:-) Will let the folks who were interested know that y'all will look into this.

Thanks,
D.

**Comment by dcollett** [comment]
+1, I've had a request for this too.

**Comment by tonyz** [comment]
Add me also. We had this previously using Javascript on our tables but alas no more. Would love to see this added.

**Comment by waitingallday** [comment]
Well, this one is certainly popular, will definitely look into including it soon!
