### ISSUE TITLE
Incorrect styling of ordered list inside unordered list

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#556]
#### Expected behaviour
Ordered lists within unordered lists should be ```list-style-type: decimal``` by default.  

#### Actual behaviour
At present, an ordered list inside an undordered list is inheriting ```list-style-type: disc```.

#### Steps to reproduce
See the second accordion on this page: https://staff.unimelb.edu.au/finance-purchasing-travel/purchasing-procurement/procurement-and-purchasing-process/

The list inside that accordion is an ordered list. 
![screen shot 2016-03-01 at 9 50 06 am](https://cloud.githubusercontent.com/assets/924501/13411762/25a64a9e-df93-11e5-85a5-582e597d1adf.png)

**Comment by waitingallday** [comment]
Good pickup! Thanks Tom

**Comment by tomstringer** [comment]
Hi guys

This isn't quite done. The straight ordered lists are working ok, but `type="a"` nested lists aren't. 

See https://staff.unimelb.edu.au/students-teaching/unpublished-content/candidature-management/leave-of-absence

![screen shot 2016-04-04 at 9 19 48 am](https://cloud.githubusercontent.com/assets/924501/14235602/aa44eab2-fa46-11e5-8dda-10eb06d8c608.png)

Displays properly here: https://staff.unimelb.edu.au/students-teaching/unpublished-content/candidature-management/leave-of-absence/steps

![screen shot 2016-04-04 at 9 20 04 am](https://cloud.githubusercontent.com/assets/924501/14235608/b91da1d2-fa46-11e5-91df-9caa5d9b7683.png)

**Comment by tomstringer** [comment]
Sorry - got to open this one more time.

This time it's unordered lists nested in ordered lists. The <ul> should appear as dot points inside the numbered list.

![screen shot 2016-05-09 at 4 28 31 pm](https://cloud.githubusercontent.com/assets/924501/15105230/3f4d1c92-1603-11e6-97f4-a6a576f61209.png)

**Comment by waitingallday** [comment]
😓

**Comment by waitingallday** [comment]
Will look into this for the next patch, sorry Tom!
