### ISSUE TITLE
Bug in class manipulation functions 

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#560]
#### Expected behaviour
(HTML) ```<span class="badge a" />```

(JS) ```mySpan.removeClass("a") ```

(Output)  ```<span class="badge" />```

#### Actual behaviour

(HTML) ```<span class="badge a" />```

(JS) ```mySpan.removeClass("a") ```

(Output)  ```<span class="bdge a" />```

#### Possible solution  

I guess the regex used at the moment isn't strict enough, and should look for a space afterwards, unless it's the last (or only) class, in which case it should check it's hitting the end of the string. 

https://github.com/marcom-unimelb/unimelb-design-system/blob/08e63ac181a660892d1cb33ec956f13e2f7b61b8/assets/shared/shims.js#L73

Or, it might be worth refactoring it with classList and a polyfill like: https://developer.mozilla.org/en/docs/Web/API/Element/classList

**Comment by patpaev** [comment]
also applies to ```hasClass()```

 #### Expected behaviour
(HTML) ```<span class="badge a" />```

(JS) ```mySpan.hasClass('ad') ```

(Output)  ```false```

#### Actual behaviour

(HTML) ```<span class="badge a" />```

(JS) ```mySpan.hasClass('ad') ```

(Output)  ```true```

**Comment by patpaev** [comment]
Or, just use the `.split(' ')` and `.join(' ')` functions rather than worrying about handling the spaces, and all of the associated fiddly edge cases.

**Comment by axelboc** [comment]
Yeah, long-standing issue. We might put in a `classList` polyfill in the next major release.
