### ISSUE TITLE
required fields on radio buttons not working with more than two buttons

### ISSUE THREAD

**Issue by dcollett** [marcom-unimelb/unimelb-design-system#567]
#### Expected behaviour
Client wants users to be able to select one of three options on a web form and wants this to be a required option.

#### Actual behaviour
Required mechanism not working.

#### Steps to reproduce
See the "preferred location" section of this form for an example:
https://nas.le.unimelb.edu.au/dcollett/forms/self-service-studio/self-service-studio.html 

The documentation at http://web.unimelb.edu.au/components/forms/ doesn't go into detail on how to implement required fields with radio buttons - I used the same technique that I successfully applied to checkboxes, having previously used the documented approach to no avail.

**Comment by axelboc** [comment]
Thanks, we'll take a look at it. In the meantime, you could use a drop-down menu instead.

**Comment by dcollett** [comment]
Thanks Alex - using a drop-down instead hadn't occurred to me, I'll use that instead.
