### ISSUE TITLE
Version number appears above search bar on web.unimelb

### ISSUE THREAD

**Issue by axelboc** [marcom-unimelb/unimelb-design-system#590]
#### Expected behaviour
The version number in the header on web.unimelb, introduced in v4.0, should not be visible when the search bar is open.

#### Actual behaviour
The version number is positioned above the search bar, even when the latter is open. No straightforward fix. The version number should probably be injected inside the header instead of before it.

#### Steps to reproduce
1. Open https://web.unimelb.edu.au
2. Click on the search button in the header.
3. The version number remains visible.

<img width="1380" alt="screen shot 2016-04-04 at 9 37 26 am" src="https://cloud.githubusercontent.com/assets/2936402/14236465/bd99acd4-fa59-11e5-98ed-986efbacd25a.png">

**Comment by waitingallday** [comment]
Fixed in #606
