### ISSUE TITLE
Small code formatting error in documentation site

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#602]
#### Expected behaviour
In-page navigation code example is broken here. Not formatting as code. 

![screenshot 2016-04-07 11 48 39](https://cloud.githubusercontent.com/assets/150315/14338037/c5783f42-fcb6-11e5-8d1b-b70d3209f58a.png)

**Comment by waitingallday** [comment]
Thanks! Will fix this ASAP
