### ISSUE TITLE
Enlarged and misaligned People Profile Page search icon

### ISSUE THREAD

**Issue by tblundell** [marcom-unimelb/unimelb-design-system#609]
NOTE: not sure if this is what is meant by issue #496.. 
Page: http://web.unimelb.edu.au/layouts/people-profile-page/
Browser: last safari vers.

#### Expected behaviour
I presume the search button/icon should sit to the right of the search text field (consistent with the header on the search page).    

#### Actual behaviour
The search icon is enlarged and sitting funky below the search text field! 

![screen shot 2016-04-18 at 9 10 45 am](https://cloud.githubusercontent.com/assets/943446/14590762/56cc27aa-0546-11e6-9c6b-676b46b4be97.png)

**Comment by waitingallday** [comment]
No, this is the new style! 😄 

The markup in that example is out of date, it should be as in http://web.unimelb.edu.au/layouts/search/

Will update it ASAP, thanks!

**Comment by waitingallday** [comment]
Fixed in https://github.com/marcom-unimelb/unimelb-design-system/commit/fc324dc45b98aa4b864c1916798dcc298e489678
