### ISSUE TITLE
events page - long email address bug (chrome)

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#640]
#### Expected behaviour
Long email addresses should remain on one line and display ellipsis at end  

#### Actual behaviour
Works in Firefox, but there is a bug in chrome if email address has a hypen i.e arts-studentprograms@unimelb.edu.au.edu.au

#### Fix
Axel says this will fix it=  **white-space: nowrap;** 

Chrome: 
![long-email-address-chrome](https://cloud.githubusercontent.com/assets/1305804/15640704/26b47a3c-267e-11e6-94f5-5991096d40d5.png)

Firefox:
![long-email-address-firefox](https://cloud.githubusercontent.com/assets/1305804/15640713/3a715856-267e-11e6-8ede-edc582e0938b.png)

**Comment by waitingallday** [comment]
It's actually doing the right thing here, the dash `-` in the email address is interpreted as a hyphen, and continuing to the next line. Not sure if there is a way to override that behaviour (beyond using an email with a dash in it)..

**Comment by waitingallday** [comment]
Oh wait, I found a way to fix it 😄

Will roll into the next release.
