### ISSUE TITLE
Degree structure enhancement

### ISSUE THREAD

**Issue by clemweth** [marcom-unimelb/unimelb-design-system#645]
### Expected behaviour
It would be good if the degree selector in the sidebar was at the top rather than hidden at the bottom of the degree structure pages such as here: [http://fvas.unimelb.edu.au/study/courses/bachelor-of-agriculture/degree-structure#degree-structure]
![screen shot 2016-06-09 at 3 42 40 pm](https://cloud.githubusercontent.com/assets/19679492/15919915/139e6010-2e59-11e6-8eb8-9a280cf93c74.png)

#### Actual behaviour
Currently hidden at the bottom. 

#### Steps to reproduce
[http://fvas.unimelb.edu.au/study/courses/bachelor-of-agriculture/degree-structure#degree-structure]

**Comment by waitingallday** [comment]
Completely agree 😄 I believe this is being looked at now.

**Comment by waitingallday** [comment]
This one was deployed to bespoke last week!
