### ISSUE TITLE
Some courses not syncing to coursesearch

### ISSUE THREAD

**Issue by clemweth** [marcom-unimelb/unimelb-design-system#647]
#### Expected behaviour
That coursesearch fee degree info should be pulled across to the bespoke degree listing (fees tab) once the course search ID is entered into the field and saved/synced.

#### Actual behaviour
A number of courses aren't syncing to coursesearch and pulling across fee info. The course codes aren't saving in the field box. It returns a value of 0 and says not yet synced after I try saving.

#### Steps to reproduce
Using chrome.
Have tried entering the course search ID for these to no avail - have also checked coursesearch to make sure they are listed correctly and with the right code:

MC-AGSC - http://fvas.unimelb.edu.au/study/courses/master-of-agricultural-sciences/industry-placements#industry-placements
GD-AGSC - http://fvas.unimelb.edu.au/study/courses/graduate-diploma-in-agricultural-sciences/fees-scholarships#fees-scholarships
GC-AGSC - http://fvas.unimelb.edu.au/study/courses/graduate-certificate-in-agricultural-sciences/fees-scholarships#fees-scholarships

![screen shot 2016-06-09 at 4 35 21 pm](https://cloud.githubusercontent.com/assets/19679492/15920914/4016690a-2e61-11e6-87a7-b20f882556d2.png)

**Comment by waitingallday** [comment]
This is actually a problem related to bespoke, not the design system. You should bring this up on the bespoke slack instead (the bespoke repo doesn't have a public issue tracker).
