### ISSUE TITLE
Display bug with ticked lists nested within an accordion

### ISSUE THREAD

**Issue by Invarti** [marcom-unimelb/unimelb-design-system#648]
#### Expected behaviour
Chris from the Melbourne School of Psychology 

The ticked style variation of the unordered list does not display as expended when nested inside an accordion. 

#### Actual behaviour
Use of the unordered list ticked style within an accordion results in both the tick and the disc being displayed. The culprit is this little bugger:

.uomcontent ul.accordion > li ul li {
  list-style-type: disc;
}

#### Steps to reproduce
Example Link: http://psychologicalsciences.unimelb.edu.au/study/current-students/study-abroad-and-exchange/

Under the section "Completing the subject equivalency assessment form"

Tested and confirmed using: 
FF 47.0
Chrome Version 50.0.2661.102 m (64-bit)
IE 11.09600.18163

**Comment by waitingallday** [comment]
Thanks Chris, we had this one reported against another project too. Will fix in the next deploy.
