### ISSUE TITLE
Internet Explorer display bug: narrow block listing containing links

### ISSUE THREAD

**Issue by Invarti** [marcom-unimelb/unimelb-design-system#649]
#### Expected behaviour
Chris from Melbourne School of Psychology

This one is for the unlucky ones that still use Internet Explorer

The narrow block listing containing 4 links does not render as expected for Internet Explorer

#### Actual behaviour
The a tags are not expanding to the correct height thereby leaving empty space between the last item and the bottom of the div container

#### Steps to reproduce

This one is in the style guide book so to speak: https://web.unimelb.edu.au/components/listings/#r6
Specifically the bottom right example that contains 4 links (more stories, more events etc)

Alternative example: http://psychologicalsciences.unimelb.edu.au/

Confirmed as a bug across 4 separate machines running various versions of Internet Explorer 11

**Comment by waitingallday** [comment]
Can confirm, this is a property that IE doesn't support properly (flexbox in a non-fixed height container). Will push out a fix in the next deploy! Thanks for reporting it.
