### ISSUE TITLE
Add tick icon

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#661]
**EDIT** Original title: "add icon for cross to supplement ticket list"

#### New feature request
Add in cross icon for use in incorrect or wrong answer. 

#### Actual behaviour
Currently we can use the ticked list icon in quiz results to indicate a correct answer. The incorrect answer is highlighted in red, but it would be good to have the option for a red cross instead.

![quiz-answers](https://cloud.githubusercontent.com/assets/1305804/16366420/612094c0-3c5a-11e6-838c-72fb27fd078e.png)

**Comment by axelboc** [comment]
Ah so at the moment, are you using a ticked list with an empty item?

```html
<ul class="ticked-list">
  <li></li>
</ul>
```

If so, then we should really add the tick as a proper icon, so it can be used with `<span class="small icon--hide-label" data-icon="tick">Correct</span>`. For the cross, there's the `close` icon. Would that do?

**Comment by yevek** [comment]
yes that would be better thanks Axel
