### ISSUE TITLE
Accomodate multi-date events in examples

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#663]
#### Expected behaviour
Currently there is no guidance around how to show multi-date events

#### Actual behaviour
It doesn't show how to do this

#### Solution
See PR https://github.com/marcom-unimelb/unimelb-design-system/pull/662

**Comment by ptagell** [comment]
live example - http://events.unimelb.edu.au/rare-book-week

**Comment by waitingallday** [comment]
Closed by #662
