### ISSUE TITLE
Accordion - option to change the font size of the heading of the accordion

### ISSUE THREAD

**Issue by siftnoorsingh** [marcom-unimelb/unimelb-design-system#667]
Currently, the heading font size of the components of an accordion is fixed. The MLS department requires that there should be an option to change the heading font size.

![screen shot 2016-07-14 at 10 50 42 am](https://cloud.githubusercontent.com/assets/13805518/16824649/df5a3f36-49b0-11e6-807b-686ab3930a24.png)

**Comment by waitingallday** [comment]
I'm going to need a reason for this?

**Comment by waitingallday** [comment]
@siftnoorsingh The components were carefully designed to be the size they are, there will need to be good usability-backed reasons for changing this

**Comment by waitingallday** [comment]
I'm going to close this issue for now, please feel free to reopen if you have more information!
