### ISSUE TITLE
Jump navigation sub-menu on research pages stopping late

### ISSUE THREAD

**Issue by jporich** [marcom-unimelb/unimelb-design-system#670]
#### Expected behaviour

Name: Jimmy Porich
Dept: External Relations/MDHS
Issue: Expecting the jump navigation to halt above all footer content when scrolling down on research pages.

#### Actual behaviour
![screen shot 2016-07-21 at 10 58 23 am](https://cloud.githubusercontent.com/assets/10070570/17008328/ababbe16-4f33-11e6-89e7-db514e214266.png)
Behaviour: On some School's Research pages the jump nav keeps scrolling past - and over the top of - the footer at the bottom of the page.

This appears to be an issue across the school level (having a quick test for example, Melbourne School of Population and Global Health [MSPGH] seems fine across all research pages, however school of Biomedicine has this issue across all research pages).

#### Steps to reproduce

Reproduced in Chrome and Firefox. See screenshot above of issue. Appears to happen to the class ".jump-navigation"

http://biomedicalsciences.unimelb.edu.au/research2/microbiology-and-immunology-research/pathogenesis-of-bacterial-infections/development-of-new-types-of-antimicrobial-agents

**Comment by yevek** [comment]
Hi @jporich MDHS has a custom paint layout for these pages -  you might want to check that.

**Comment by jporich** [comment]
Appears it has to do with early applying of the ".endpoint" class to ".jump-navigation". Will see if I can track down where this is being applied from.

**Comment by waitingallday** [comment]
Yes, that's just where the design system identifies the bottom of content, but this was written long before these layouts ever existed - it's probably triggering early because it doesn't identify the footer.

**Comment by jporich** [comment]
Yup. Seems to be an issue with an accidental div causing the system to not identify the footer. 

Looks like there is a Squiz Matrix auto-generated div being put around the footer on the broken pages. 

Both working and non-working pages share the same Custom Paint Layout though (which doesn't appear include footer information/generation). Any chance someone who has access to the footer paint layout can see why there'd be an auto-generating Squiz Container being created? Doesn't seem to be anything caused by settings/metadata. 

If it was caused by metadata I would imagine it would be caused by the system attempting to add some Social Media in that area and failing?

NOT WORKING:
![screen shot 2016-07-21 at 1 32 23 pm copy](https://cloud.githubusercontent.com/assets/10070570/17010484/bdcd5cbc-4f47-11e6-904b-0eb7204d0199.png)

 WORKING:
![screen shot 2016-07-21 at 1 29 09 pm copy](https://cloud.githubusercontent.com/assets/10070570/17010436/4d7002d0-4f47-11e6-836e-af9416a9b310.png)

**Comment by yevek** [comment]
Hi @jporich go and have a look at the footer asset for that site #1460348 and you'll that the page that is being nested has been set to a DIV instead of RAW HTML. 

![footer-div](https://cloud.githubusercontent.com/assets/1305804/17010643/2efb8886-4f49-11e6-8f21-a94ef57b7e19.png)

**Comment by waitingallday** [comment]
@jporich did you manage to sort this out in matrix, or do we need to fix it at the design system level?

**Comment by jporich** [comment]
Hi Jason,

Sorry for not getting back on this one, been running around at another department this week.

We managed to track it down:

The footer was being contained in a WSYWIG container, which adds it’s own squiz matrix id on to the element block.

Fix is simply transferring it over to a raw HTML container so nothing like “id=new_content_creator_324323” is created (and doesn’t mess up CSS selectors).

I’ve just got to find where MDHS has their footer layout is all to make the adjustment.

Thanks for chasing this one up, I should have a chance to get at it tomorrow when I’m back at MDHS

Jimmy

Jimmy Porich  |  Web Content and Development Coordinator
External Relations  |  University Services

Level 2, 32 North Lincoln Square
The University of Melbourne, Victoria 3010 Australia
T: (03) 9035 8072 E: james.porich@unimelb.edu.au<mailto:james.porich@unimelb.edu.au>


[cid:image001.png@01D1E74F.506230E0]


This email and any attachments may contain personal information or  information that is otherwise confidential or the subject of copyright. Any use, disclosure or copying of any part of it is prohibited. The University does not warrant that this email or any attachments are free from viruses or defects. Please check any attachments for viruses and defects before opening them. If this email is received in error please delete it and notify us by return email.

-

**Comment by yevek** [comment]
@waitingallday you can close this bug off @jporich has located and fixed the issue.
