### ISSUE TITLE
Description text movement on Staff Hub > 4.3 release

### ISSUE THREAD

**Issue by simpsonatti** [marcom-unimelb/unimelb-design-system#683]
#### Expected behaviour
Helen Simpson from Internal Communications (External Relations) - description text on Staff Hub should be aligned with the other text as it was prior to upgrade to 4.3.

#### Actual behaviour
Description text is displaying left of the rest of the text on the page.

#### Steps to reproduce
See https://staff.unimelb.edu.au/diversity-inclusion/equity-campaign
or any standard page on Staff Hub.
![screen shot 2016-07-27 at 12 10 19 pm](https://cloud.githubusercontent.com/assets/17016472/17163360/ed521df6-5401-11e6-9765-ec13ccb0b160.png)
Compare with attached screenshot of how it used to look.

Thanks
Helen

**Comment by waitingallday** [comment]
Thanks Helen - that is actually the correct behaviour in line with the initial designs, everything previous to 4.3 was incorrect due to the confused source order. I can see looking at the pages now and your screen above what you're trying to achieve - I think we'll need to create a new style for this.

**Comment by simpsonatti** [comment]
Thanks for getting back to me so quickly. If it's not a huge job, can you please proceed with the new styling?  What would be the timeframe for this? Thanks

**Comment by waitingallday** [comment]
Sorry, we were just discussing this internally and it is indeed a regression. Will push out a fix with the next deploy.

**Comment by simpsonatti** [comment]
Perfect, thanks Jason!
