### ISSUE TITLE
<textarea> and  <input type="text"> 'placeholder' text are different shades

### ISSUE THREAD

**Issue by tblundell** [marcom-unimelb/unimelb-design-system#699]
The 'placeholder' text in the `<input type="text">` is a darker shade than placeholder text in `<textarea>`, and is quite close to the actual entered in text colour
 
![screen shot 2016-08-12 at 9 30 49 am](https://cloud.githubusercontent.com/assets/943446/17608455/ec64d756-606f-11e6-9781-91c0f36a564e.png)
#### Expected behaviour
The placeholder text shade should match on both elements

#### Actual behaviour
`<textarea>` and  `<input type="text">` 'placeholder' text are different shades. 
There is a risk that darker placeholder text in `<input type="text">` may be mistaken for entered text.   
 
#### Steps to reproduce
just build a form with both elements... or enter a placeholder value within the code on this page to reproduce quickly http://web.unimelb.edu.au/components/forms/#text-field

**Comment by waitingallday** [comment]
Thanks Tim 🙂
