### ISSUE TITLE
Map embed in docs is broken 

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#700]
The maps `<iframe/>` under the **SINGLE DATE EVENT PAGE MIXED MARKUP** example on the [Events component](http://web.unimelb.edu.au/components/events/) is now also wrapped in the design system.

I'm guessing the embed code might have changed has part of this announcement? 
https://unimelb.slack.com/archives/web/p1470207742000009

<img width="1132" alt="screen shot 2016-08-12 at 1 23 49 pm" src="https://cloud.githubusercontent.com/assets/6847023/17612026/207acb84-6090-11e6-98d4-fc00b974f04d.png">

**Comment by woowoowoo** [comment]
Patrick,
the quick fix is to change the src of the iframe to https instead of the current protocol relative link.

I have a ticket in with Squiz asking about this, but for some reason forcing https (which I've done for geolocation) is stripping the query string from the URL

Cheers. Andrew H

**Comment by waitingallday** [comment]
This is looking good now, will close the issue. Ideally, I want to replace the existing openstreetmap (leaflet) maps component with one that calls to our own maps.unimelb embed. Something for another day!
