### ISSUE TITLE
Padding issue with call to action  buttons when lists are used on Staff Hub

### ISSUE THREAD

**Issue by simpsonatti** [marcom-unimelb/unimelb-design-system#703]
#### Expected behaviour
Helen Simpson, Internal Communications (External Relations)
There should be padding above the call to action button when using lists and call to action buttons within Staff Hub accordions.

#### Actual behaviour
There is no padding

#### Steps to reproduce
Please see screenshots attached showing how this renders correctly when lists are not used.
![padding - incorrect](https://cloud.githubusercontent.com/assets/17016472/17654360/ad957b20-62e5-11e6-839d-351886c6e6a5.png)
![padding - correct](https://cloud.githubusercontent.com/assets/17016472/17654362/aea20290-62e5-11e6-911e-04b3a41db1f5.png)

Thanks
Helen

**Comment by waitingallday** [comment]
Hi Helen, there have been a lot of changes to the lists lately - will look into this ASAP

**Comment by rothenburycam** [comment]
Just adding to this - looks like the problem is padding on the `ul` rather than the CTA button.

![screen shot 2016-08-16 at 11 20 20 am](https://cloud.githubusercontent.com/assets/11714609/17684989/76f1a756-63a3-11e6-825b-13d257baf826.png)

**Comment by simpsonatti** [comment]
Hi @waitingallday, just following up on this one. I've had another person raise this, as it's particularly prominent when headings are used, but the issue does not occur when the accordion asset is opened by itself. Are you able to provide an ETA for a fix please? 
![accordion asset](https://cloud.githubusercontent.com/assets/17016472/18294715/94d069e6-74de-11e6-8477-87acd6f548ef.png)

![accordion opened up](https://cloud.githubusercontent.com/assets/17016472/18294697/78f6479a-74de-11e6-91e7-1dbf59a5517e.png)

**Comment by waitingallday** [comment]
Hi Helen (& Cam), I'm just pushing up a fix now that will go into the next release v5.0. Can I just note that the accordion was never intended to display this much content though - it was originally designed to contain a paragraph or two of text at most. If you have a full page of content within the accordion, then I would suggest you find a different way of organising it.

ie. the accordions on https://staff.unimelb.edu.au/marketing-communications/marketing-branding-advertising/create-a-unique-logo-and-identity could sit directly on the page instead - there is no value in hiding essential information on this page, and the accordion trigger is only really used as a subheading.

**Comment by simpsonatti** [comment]
Thanks, Jason.

Yep, I agree about the use of accordions. The content pages on those marketing pages are about to undergo a big redevelopment so this should improve.

Kind regards,
..........................................................................
Helen Simpson | Web Content Officer - Internal Communications
External Relations
University of Melbourne, VIC 3010
Email helen.simpson@unimelb.edu.au<mailto:helen.simpson@unimelb.edu.au>

[cid:601A43E3-1586-4DD2-8447-93082107B641]


This email and any attachments may contain personal information or  information that is otherwise confidential or the subject of copyright. Any use, disclosure or copying of any part of it is prohibited. The University does not warrant that this email or any attachments are free from viruses or defects. Please check any attachments for viruses and defects before opening them. If this email is received in error please delete it and notify us by return email.
