### ISSUE TITLE
Filtered listing - Accessibility

### ISSUE THREAD

**Issue by anormand** [marcom-unimelb/unimelb-design-system#705]
#### Expected behaviour
Section headings in filtered listing should be part of the main content

#### Actual behaviour
Section headings are placed within an `<aside>` tag which maps to the ARIA role of complementary

#### Steps to reproduce
Using either JAWS and IE, or NVDA and Firefox, go to: https://openday.unimelb.edu.au/plan-my-day
Arrow down to 'Undergraduate Studies' and it will be identified as a complementary landmark

**Comment by waitingallday** [comment]
I propose we use `<div class="aside">` rather than the semantic `<aside>` element - we were using this structure more out of convenience, reusing existing styles. This will be a breaking change.

**Comment by waitingallday** [comment]
Fixed in #716 🙌
