### ISSUE TITLE
Alternate accordion behaviour

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#707]
Gordon McKenzie has asked for new functionality in the design system, based on the Programs panel of: https://online.usc.edu/ (scroll down a bit).

Behaviour is similar to tabs or accordions.

#### Expected behaviour
I mocked up a simple example based on our accordion markup https://jsbin.com/kedibi/

At smaller screen sizes (where side by side layout is impractical) the component would revert to standard accordion behaviour.

**Comment by yevek** [comment]
I think we already have this functionality here: https://cms.unimelb.edu.au/controlled-environment/templates/special/sidebar ?

**Comment by woowoowoo** [comment]
Hmm - yes, that's the functionality, but it's only available as a whole-of-page option, isn't it?
Can't just be used on a section, can it?

**Comment by waitingallday** [comment]
It was designed as a whole-page thing, but we might be able to modularise it a bit more if it doesn't work out - it's effectively using the same code as the navigation tabs

**Comment by yevek** [comment]
I haven't tried doing this, but it works with other things where you set up the page and functionality how you want, and then call it using %globals_asset_contents_raw:xxxx% where xxxx equals the parent asset page. Could work in the meantime, but it would be handy to have similar to tabs. Depends on the purpose though.

**Comment by axelboc** [comment]
Yeah it's more tabs than accordion. PR #607 actually includes a big refactoring of the sidebars tabs to remove their coupling with other components (such as the sidebar layout and horizontal tabs). So they should become a lot more portable once the changes are released.

**Comment by waitingallday** [comment]
Sidebar layout properly documented in #607
