### ISSUE TITLE
Anchor links don't work with in-page tabs

### ISSUE THREAD

**Issue by foleye** [marcom-unimelb/unimelb-design-system#713]
#### Expected behaviour
Click on url with anchor tag, page loads with focus on the corresponding tab.
Erica from Alumni - required asap (as usual).

#### Actual behaviour
Doesn't apply current property to the anchored tab (page is in default state).

#### Steps to reproduce
http://web.unimelb.edu.au/components/tabs/#third-tab
![screen shot 2016-08-29 at 12 56 38 pm](https://cloud.githubusercontent.com/assets/11880447/18039641/1d9aeb5a-6de8-11e6-85b1-ecf256c2cbb4.png)

**Comment by waitingallday** [comment]
Sorry, not sure I understand the problem - in page tabs will not open at the clicked tab, that was a choice we made earlier. Only nav tabs will have this behaviour, in page tabs only function within a page.

**Comment by foleye** [comment]
Did this change from earlier implementations? It seems to work on our original site. Anyway, thanks for the info – you can close off the issue in that case.

Cheers,
Erica

**Comment by waitingallday** [comment]
Hi Erica, just had a look now, it was in the v3.8 release that this was removed. You're right - it did work previously but it was never meant to, and the implementation was not very fault tolerant.
