### ISSUE TITLE
Spacing between two column layout

### ISSUE THREAD

**Issue by arts-unimelb** [marcom-unimelb/unimelb-design-system#734]
Hi everyone how do I put some padding between a two column layout so the text has a little more space please? See screenshot
http://arts.unimelb.edu.au/rupc#partners
![two-column-spacing](https://cloud.githubusercontent.com/assets/1032902/18694084/87d13c2c-7fea-11e6-983b-3c4bed987f31.jpg)

**Comment by patpaev** [comment]
@arts-unimelb you need to remove the `.tight` class you have applied to the `section` tags. That class gets rid of the padding.

**Comment by waitingallday** [comment]
Thanks Pat! Good advice. May I also add that this is not the intended use of the 2-col component - every page on a design system site should be linear (1-col). I can see there's a lot of content here, but as a user I have no idea of where to start, or what order it follows. You already have a summary listing of the names above, perhaps you could use them as jump links to the related paragraph below?
