### ISSUE TITLE
Article page on web.unimelb has no video

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#737]
#### Expected behaviour
The example article page: https://web.unimelb.edu.au/layouts/article/ should have a header image, or video.

#### Actual behaviour
The page the old 'video background article header', but the video files are a 404.
The 'video background article header' no longer appears on the 'headers' components page, has it been deprecated?
The header appears to reference an image as a fallback, but, although the image is there, I just see a black background.

**Comment by waitingallday** [comment]
Yes, the video background no longer works in modern browsers. It was never really supported in any version of the design system - that particular layout is also deprecated in the newest version. Sorry for the confusion!
