### ISSUE TITLE
v5.0 Blockquote no maxwidth 

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#739]
#### Expected behaviour
Quotes should probably have a max width so they don't stretch across page.

#### Actual behaviour
New v5.0 blockquotes expand full width of page regardless if wrapped in section.

#### Steps to reproduce
Check out this site or see screenshots below 
http://cms.unimelb.edu.au/controlled-environment/mcetest/home/_recache

![new-block-quote](https://cloud.githubusercontent.com/assets/1305804/18941413/4f869ebe-8654-11e6-8769-172028cbc1a1.png)

Classic block quote has maxwidth. 
![block-quote-classic](https://cloud.githubusercontent.com/assets/1305804/18941500/15f1efe0-8655-11e6-8170-6261fff9235a.png)

**Comment by waitingallday** [comment]
Fixed by #744
