### ISSUE TITLE
ol brackets class spacing (RE: Pull request #680)

### ISSUE THREAD

**Issue by rhyslawry** [marcom-unimelb/unimelb-design-system#742]
#### Expected behaviour
"brackets" class was added to ol for legal documentation as per pull request #680
(1)
(2)
etc.

#### Actual behaviour
Numbers overlap the text when counter reaches two digits.

We have changed the left spacing from -1.6em to -2em
`.uomcontent ol.brackets li::before {
    content: "(" counter(list1, decimal) ") ";
    counter-increment: list1;
    left: -2em;
    position: absolute;
}`

Want this change to be implemented in the design system

#### Steps to reproduce
Example here: https://cms.unimelb.edu.au/unimelb/governance/university-of-melbourne-statute/council-regulation/_recache
Under heading "6 Conduct of council elections"

**Comment by waitingallday** [comment]
Fixed by #743
