### ISSUE TITLE
Sidebar tab nav - scroll to top behaviour

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/unimelb-design-system#749]
Reported by Gordon McKenzie on Zendesk ticket #6094

#### Expected behaviour
When selecting the sidebar tabbed nav on this page: https://online.unimelb.edu.au/, don't scroll to top tabbed nav bar.

#### Actual behaviour
Scrolls to the top when you select one of the sidebar tabbed nav elements.

#### Steps to reproduce
See: http://screencast.com/t/7bvDtWKl9Dq

**Comment by yevek** [comment]
FYI - I've tried Chrome, Firefox and Safari on Mac and seems fine - can't really tell what browser this is by screencast

**Comment by tomstringer** [comment]
@yevek I've tested with Safari and Firefox. You need to be scrolled down (so that the sidebar tabbed nav sits at the top of the screen) first.

**Comment by yevek** [comment]
This is what I'm seeing in Chrome v54.0.2840.71, Firefox v49.0.2 and Safari v8.0.5 on Mac.

Clicked on study tab, then clicked on sidebar tab nav content. 
http://screencast.com/t/2LwiEDXYExA

Scrolled down to sidebar tab nav content
http://screencast.com/t/NVrQTqUahe 

both look ok to me.

**Comment by axelboc** [comment]
It's meant to scroll to the top of the sidebar tabs, not the full-width tabs. If the sidebar tabs were further down the page, or when they're viewed on mobile/tablet, it's very annoying to have to scroll back down every time. Also, if you visit https://online.unimelb.edu.au/#padmin, you expect it to scroll to the sidebar tabs, not to the full-width tab. I've implemented this feature, but there must be a bug somewhere. I'll take a look at it asap.

**Comment by axelboc** [comment]
Gordon managed to fix the issue. It wasn't a bug in the sidebar tabs component.
