### ISSUE TITLE
Issue with bolding presenter's name in event details page

### ISSUE THREAD

**Issue by dasithds** [marcom-unimelb/unimelb-design-system#768]
Hey guys,

There is an issue with how presenter's names are bolded on the event details page. On the main page itself, it works fine and the presenter's name is in bold but if you click on their name at the bottom of the page, the popup still contains ** markup instead of bolding the text. 

http://arts.unimelb.edu.au/news/details?event=7852

A screenshot is attached.
![news_detail](https://cloud.githubusercontent.com/assets/16767361/20582894/479c07e6-b239-11e6-868a-3151af54ca61.png)

Thanks,
Dasith.

**Comment by waitingallday** [comment]
Hi, this isn't a design system problem - seems like it's not rendering the markdown source in the modal.
