### ISSUE TITLE
File type and size addition for downloadable in-page documents - Staff Hub

### ISSUE THREAD

**Issue by allanaw** [marcom-unimelb/unimelb-design-system#774]
#### Expected behaviour
In the staff hub (and other sites) there is no file type and size specified for downloadable documents... that I'm aware of. For in-page links, it's not clear what the link action is.
For accessibility, I'm suggesting we create a class for doc download links to automatically append the doc type and size. Eg. 'Download the brochure (PDF, 222KB)'. This information could be added manually, but for consistency, a class may be able to pull the asset attributes automatically.

#### Actual behaviour
No existing function in the design system for downloadable doc type and size.

#### Steps to reproduce
Eg. https://staff.unimelb.edu.au/academic-services/unpublished-content/induction-and-orientation/_nocache
All items in column one of the table are downloadable Word docs. Ideally, it would be good to add the file type and size at the end of the link so the user is aware of the action when clicking the link.

This is just a suggestion, I'm keen to hear your thoughts on best practice and the best way to set this up in the back end, if at all.

Thanks,
Allana

**Comment by yevek** [comment]
Hi @allanaw this style is already available: http://web.unimelb.edu.au/components/icons/#hidden-label and if the lists of documents are dynamically generated using an asset listing in Staff Hub it's possible to do this automatically. I couldn't access that page however to check how you are adding documents. Can you please add a screenshot?

**Comment by yevek** [comment]
Allana I can see that you have documents listed individually on this page: https://staff.unimelb.edu.au/academic-services/academic-services-toolkit

Here is the markup you can use to get the following style:

![markup](https://cloud.githubusercontent.com/assets/1305804/21034979/06faf246-be10-11e6-8bbd-922df818ce76.png)

![document download style](https://cloud.githubusercontent.com/assets/1305804/21034976/004151f2-be10-11e6-914b-f3ac0129decd.png)

**Comment by allanaw** [comment]
Sorry - I posted the wrong link...

I have added the asset summary and icon in safe mode to this page:
https://staff.unimelb.edu.au/academic-services/our-people/induction-and-orientation/_nocache

Is this something you would recommend adding for downloadable docs going forward? I don't want to start doing this if it's not general practice... but if you're ok with it, I'll start using it for all future docs.

**Comment by yevek** [comment]
I think it looks a bit hard to read when document type and size are included and since the file sizes are so small it’s just extra noise. I’d probably only add the the size if they are HUGE and even so, it’s probably not necessary on Staff Hub given that majority of users are using desktop (not mobile) to download resources. 

It is helpful to use the download markup if you don't mind the extra work.

![document](https://cloud.githubusercontent.com/assets/1305804/21036266/dde3e896-be18-11e6-8f13-bea6ced3023a.png)

**Comment by allanaw** [comment]
Great advice! Thanks Donna... makes perfect sense.

Going by your screen shot above, are you also hinting that the 'Document' column should be switched to column two? :)

Thanks again - have a great weekend.

**Comment by yevek** [comment]
RE: document column - it probably doesn't matter too much as long as you are consistent within the site.

**Comment by allanaw** [comment]
Thanks.
