### ISSUE TITLE
Smoothscroll for tabs needs an offset to account for the fixed header

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#82]
Currently, when clicking on a tab, it will scroll the page to the top of the tabs, but since the introduction of the fixed header, there should be a ~40px top offset so the text in the tabs is not obscured.

Currently:  
![screen shot 2014-10-28 at 10 56 45 am](https://cloud.githubusercontent.com/assets/6847023/4801864/f02ccc7a-5e39-11e4-9c27-5944963e0f0b.png)

Should be:  
![screen shot 2014-10-28 at 11 27 56 am](https://cloud.githubusercontent.com/assets/6847023/4801871/042d8976-5e3a-11e4-80dd-29b73d0a10c0.png)

**Comment by tomstringer** [comment]
Just chucking in a +1 for this, though I've noticed that it's not consistent across browsers. Works as it should in Firefox, but not in Safari - see screen capture here (first browser is Firefox, second is Safari): http://screencast.com/t/2rym7OMh
